# -----------------------------------------------------------------------------
#	SGI OpenGL Sample Implementation -- Font library
# -----------------------------------------------------------------------------

default.exit:: libGLfont.so

CC_LIBS = GL

libGLfont.so:		\
	libGLfont.o	\
	glfont.o
