# -----------------------------------------------------------------------------
#	SGI OpenGL Sample Implementation -- glutilities library
# -----------------------------------------------------------------------------

default.exit:: libglut.so

CC_LIBS = GL X11

libglut.so: libglut.o	\
	glut_8x13.o	\
	glut_9x15.o	\
	glut_bitmap.o	\
	glut_cindex.o	\
	glut_dials.o	\
	glut_dstr.o	\
	glut_event.o	\
	glut_ext.o	\
	glut_get.o	\
	glut_init.o	\
	glut_input.o	\
	glut_mesa.o	\
	glut_menu.o	\
	glut_shapes.o	\
	glut_space.o	\
	glut_stroke.o	\
	glut_tablet.o	\
	glut_teapot.o	\
	glut_tr10.o	\
	glut_tr24.o	\
	glut_util.o	\
	glut_win.o	\
	glut_winmisc.o	\
	layerutil.o
