# -----------------------------------------------------------------------------
#	SGI OpenGL Sample Implementation -- Device Dependent Xserver Code
# -----------------------------------------------------------------------------

default.exit:: lib.a

CC_OPT += -D_LANGUAGE_C

lib.a:			\
	ddxci.o		\
	ddxcx.o		\
	ddxrgb.o	\
	ddxscreens.o
