#!/bin/sh

if test -f .config
then
	source .config
fi

DIR_BUILD=`pwd -P`
DIR_SOURCE=$DIR_TOP_SOURCE`echo $DIR_BUILD | sed s%$DIR_TOP_BUILD%%`

HTF_SOURCE=$1

source $HTF_SOURCE > /dev/null

#	document header
#
if [ "$HTF_HEADER" != "no" ]
then
cat <<end-of-header
<html>
<head>	<title>${HTF_TITLE:-No title set}</title>
	<meta name="Description" content="$HTF_DESCRIPTION">
	<meta name="Keywords" content="$HTF_KEYWORDS">
	<meta name="Author" content="$HTF_AUTOR">
</head><frameset cols="${HTF_MENU_WIDTH:-180}, *" border=0>
	<frame src="menu.$HTF_LANGUAGE.html" name="menu">
	<frame src="welcome.$HTF_LANGUAGE.html" name="this-page">
<noframes><body text="${HTF_COLOR_TEXT:-#000000}" bgcolor="${HTF_COLOR_BGCOLOR:-#FFFFFF}" link="${HTF_COLOR_LINK:-#0000EE}" vlink="${HTF_COLOR_VLINK:-#551A8B}" alink="${HTF_COLOR_ALINK:-#FF0000}" background="$HTF_IMAGE_BACKGROUND">
end-of-header
fi

echo ${HTF_DOCUMENT_TITLE:-"<h1><hr noshade>${HTF_LONG_TITLE:-$HTF_TITLE}<hr noshade></h1>"}

#	document body
#
source $HTF_SOURCE 

#	document trailer
#
if [ "$HTF_TRAILER" != "no" ]
then
	case $HTF_LANGUAGE in
	en)	HTF_BACK="back"
		HTF_MAINTAINED1="This page is maintained by "
		HTF_MAINTAINED2="."
		;;
	de)	HTF_BACK="zur&uuml;ck"
		HTF_MAINTAINED1="Diese Seite wird von "
		HTF_MAINTAINED2=" betreut."
		;;
	*)	echo "htf2html/htf2html.sh: unknown language $HTF_LANGUAGE."
		exit 1
	esac
	
	cat <<end-of-trailer

<p><hr noshade>
<table cols=3 width="100%"><tr valign=top>
<td align=left><i><a target="_top" href="${HTF_BACKLINK:-../index.$HTF_LANGUAGE.html}">$HTF_BACK</a></i></td>
<td align=center><i>\$Revision ${HTF_REVISION:-&nbsp;}</i></td>
<td align=right><i>$HTF_MAINTAINED1 <a href="$HTF_MAINTAINER_URL">$HTF_MAINTAINER</a>$HTF_MAINTAINED2</i></td>
</tr></table>
</body></noframes>
</frameset></html>
end-of-trailer
fi
