# -----------------------------------------------------------------------------
#	OpenGL SI Device Independent Xserver Code
# -----------------------------------------------------------------------------


default.exit:: lib.a

lib.a:			\
	global.o	\
	glxbuf.o	\
	glxcmds.o	\
	glxcmdsswap.o	\
	glxext.o	\
	glxfb.o		\
	glximports.o	\
	glxmem.o	\
	glxpix.o	\
	glxscreens.o	\
	glxutil.o	\
	render2.o	\
	render2swap.o	\
	renderpix.o	\
	renderpixswap.o	\
	rensize.o	\
	rensizetab.o	\
	single2.o	\
	single2swap.o	\
	singlepix.o	\
	singlepixswap.o	\
	singlesize.o	\
	xfont.o		\
	g_disptab.o	\
	g_disptab_EXT.o	\
	g_render.o	\
	g_renderswap.o	\
	g_single.o	\
	g_singleswap.o

