
default.exit:: lib.aa


CC_OPT_TARGET = -DLIBRARYBUILD -DNDEBUG 

#	note: glinterface.cc 
#

INTERFACE_OBJECTS =		\
	bezierEval.oo		\
	bezierPatch.oo		\
	bezierPatchMesh.oo	\
	glcurveval.oo		\
	glrenderer.oo		\
	glsurfeval.oo		\
	incurveeval.oo		\
	insurfeval.oo

INTERNAL_OBJECTS =		\
	arc.oo			\
	arcsorter.oo		\
	arctess.oo		\
	backend.oo		\
	basiccrveval.oo		\
	basicsurfeval.oo	\
	bin.oo			\
	bufpool.oo		\
	cachingeval.oo		\
	ccw.oo			\
	coveandtiler.oo		\
	curve.oo		\
	curvelist.oo		\
	curvesub.oo		\
	dataTransform.oo	\
	displaylist.oo		\
	flist.oo		\
	flistsorter.oo		\
	hull.oo			\
	intersect.oo		\
	knotvector.oo		\
	mapdesc.oo		\
	mapdescv.oo		\
	maplist.oo		\
	mesher.oo		\
	monoTriangulationBackend.oo \
	monotonizer.oo		\
	mycode.oo		\
	nurbsinterfac.oo	\
	nurbstess.oo		\
	patch.oo		\
	patchlist.oo		\
	quilt.oo		\
	reader.oo		\
	renderhints.oo		\
	slicer.oo		\
	sorter.oo		\
	splitarcs.oo		\
	subdivider.oo		\
	tobezier.oo		\
	trimline.oo		\
	trimregion.oo		\
	trimvertpool.oo		\
	uarray.oo		\
	varray.oo

TESSELATOR_OBJECTS =		\
	directedLine.oo		\
	gridWrap.oo		\
	monoChain.oo		\
	monoTriangulation.oo	\
	partitionX.oo		\
	partitionY.oo		\
	polyDBG.oo		\
	polyUtil.oo		\
	primitiveStream.oo	\
	quicksort.oo		\
	rectBlock.oo		\
	sampleComp.oo		\
	sampleCompBot.oo	\
	sampleCompRight.oo	\
	sampleCompTop.oo	\
	sampleMonoPoly.oo	\
	sampledLine.oo		\
	searchTree.oo		\
	monoPolyPart.oo

lib.aa: $(INTERFACE_OBJECTS) $(INTERNAL_OBJECTS) $(TESSELATOR_OBJECTS)

