/* DO NOT EDIT - THIS FILE IS AUTOMATICALLY GENERATED */

/*
** License Applicability. Except to the extent portions of this file are
** made subject to an alternative license as permitted in the SGI Free
** Software License B, Version 1.1 (the "License"), the contents of this
** file are subject only to the provisions of the License. You may not use
** this file except in compliance with the License. You may obtain a copy
** of the License at Silicon Graphics, Inc., attn: Legal Services, 1600
** Amphitheatre Parkway, Mountain View, CA 94043-1351, or at:
**
** http://oss.sgi.com/projects/FreeB
**
** Note that, as provided in the License, the Software is distributed on an
** "AS IS" basis, with ALL EXPRESS AND IMPLIED WARRANTIES AND CONDITIONS
** DISCLAIMED, INCLUDING, WITHOUT LIMITATION, ANY IMPLIED WARRANTIES AND
** CONDITIONS OF MERCHANTABILITY, SATISFACTORY QUALITY, FITNESS FOR A
** PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
**
** Original Code. The Original Code is: OpenGL Sample Implementation,
** Version 1.2.1, released January 26, 2000, developed by Silicon Graphics,
** License Applicability. Except to the extent portions of this file are
** made subject to an alternative license as permitted in the SGI Free
** Software License B, Version 1.1 (the "License"), the contents of this
** file are subject only to the provisions of the License. You may not use
** this file except in compliance with the License. You may obtain a copy
** of the License at Silicon Graphics, Inc., attn: Legal Services, 1600
** Amphitheatre Parkway, Mountain View, CA 94043-1351, or at:
** 
** http://oss.sgi.com/projects/FreeB
** 
** Note that, as provided in the License, the Software is distributed on an
** "AS IS" basis, with ALL EXPRESS AND IMPLIED WARRANTIES AND CONDITIONS
** DISCLAIMED, INCLUDING, WITHOUT LIMITATION, ANY IMPLIED WARRANTIES AND
** CONDITIONS OF MERCHANTABILITY, SATISFACTORY QUALITY, FITNESS FOR A
** PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
** 
** Original Code. The Original Code is: OpenGL Sample Implementation,
** Version 1.2.1, released January 26, 2000, developed by Silicon Graphics,
** Inc. The Original Code is Copyright (c) 1991-2000 Silicon Graphics, Inc.
** Copyright in any portions created by third parties is as indicated
** elsewhere herein. All Rights Reserved.
** 
** Additional Notice Provisions: The application programming interfaces
** established by SGI in conjunction with the Original Code are The
** OpenGL(R) Graphics System: A Specification (Version 1.2.1), released
** April 1, 1999; The OpenGL(R) Graphics System Utility Library (Version
** 1.3), released November 4, 1998; and OpenGL(R) Graphics with the X
** Window System(R) (Version 1.3), released October 19, 1998. This software
** was created using the OpenGL(R) version 1.2.1 Sample Implementation
** published by SGI, but has not been independently verified as being
** compliant with the OpenGL(R) version 1.2.1 Specification.
**
*/

#include "types.h"
#include "GL/gl.h"
#include "context.h"
#include "g_disp.h"

void GLAPI glNewList( GLuint list, GLenum mode)
{
    (*__gl_dispatch.dispatch.NewList)(list, mode);
}

void GLAPI glEndList( void)
{
    (*__gl_dispatch.dispatch.EndList)();
}

void GLAPI glCallList( GLuint list)
{
    (*__gl_dispatch.dispatch.CallList)(list);
}

void GLAPI glCallLists( GLsizei n, GLenum type, const GLvoid *lists)
{
    (*__gl_dispatch.dispatch.CallLists)(n, type, lists);
}

void GLAPI glDeleteLists( GLuint list, GLsizei range)
{
    (*__gl_dispatch.dispatch.DeleteLists)(list, range);
}

GLuint GLAPI glGenLists( GLsizei range)
{
    return (*__gl_dispatch.dispatch.GenLists)(range);
}

void GLAPI glListBase( GLuint base)
{
    (*__gl_dispatch.dispatch.ListBase)(base);
}

void GLAPI glBegin( GLenum mode)
{
    (*__gl_dispatch.dispatch.Begin)(mode);
}

void GLAPI glBitmap( GLsizei width, GLsizei height, GLfloat xorig, GLfloat yorig, GLfloat xmove, GLfloat ymove, const GLubyte *bitmap)
{
    (*__gl_dispatch.dispatch.Bitmap)(width, height, xorig, yorig, xmove, ymove, bitmap);
}

void GLAPI glColor3b( GLbyte red, GLbyte green, GLbyte blue)
{
    (*__gl_dispatch.dispatch.Color3b)(red, green, blue);
}

void GLAPI glColor3bv( const GLbyte *v)
{
    (*__gl_dispatch.dispatch.Color3bv)(v);
}

void GLAPI glColor3d( GLdouble red, GLdouble green, GLdouble blue)
{
    (*__gl_dispatch.dispatch.Color3d)(red, green, blue);
}

void GLAPI glColor3dv( const GLdouble *v)
{
    (*__gl_dispatch.dispatch.Color3dv)(v);
}

void GLAPI glColor3f( GLfloat red, GLfloat green, GLfloat blue)
{
    (*__gl_dispatch.dispatch.Color3f)(red, green, blue);
}

void GLAPI glColor3fv( const GLfloat *v)
{
    (*__gl_dispatch.dispatch.Color3fv)(v);
}

void GLAPI glColor3i( GLint red, GLint green, GLint blue)
{
    (*__gl_dispatch.dispatch.Color3i)(red, green, blue);
}

void GLAPI glColor3iv( const GLint *v)
{
    (*__gl_dispatch.dispatch.Color3iv)(v);
}

void GLAPI glColor3s( GLshort red, GLshort green, GLshort blue)
{
    (*__gl_dispatch.dispatch.Color3s)(red, green, blue);
}

void GLAPI glColor3sv( const GLshort *v)
{
    (*__gl_dispatch.dispatch.Color3sv)(v);
}

void GLAPI glColor3ub( GLubyte red, GLubyte green, GLubyte blue)
{
    (*__gl_dispatch.dispatch.Color3ub)(red, green, blue);
}

void GLAPI glColor3ubv( const GLubyte *v)
{
    (*__gl_dispatch.dispatch.Color3ubv)(v);
}

void GLAPI glColor3ui( GLuint red, GLuint green, GLuint blue)
{
    (*__gl_dispatch.dispatch.Color3ui)(red, green, blue);
}

void GLAPI glColor3uiv( const GLuint *v)
{
    (*__gl_dispatch.dispatch.Color3uiv)(v);
}

void GLAPI glColor3us( GLushort red, GLushort green, GLushort blue)
{
    (*__gl_dispatch.dispatch.Color3us)(red, green, blue);
}

void GLAPI glColor3usv( const GLushort *v)
{
    (*__gl_dispatch.dispatch.Color3usv)(v);
}

void GLAPI glColor4b( GLbyte red, GLbyte green, GLbyte blue, GLbyte alpha)
{
    (*__gl_dispatch.dispatch.Color4b)(red, green, blue, alpha);
}

void GLAPI glColor4bv( const GLbyte *v)
{
    (*__gl_dispatch.dispatch.Color4bv)(v);
}

void GLAPI glColor4d( GLdouble red, GLdouble green, GLdouble blue, GLdouble alpha)
{
    (*__gl_dispatch.dispatch.Color4d)(red, green, blue, alpha);
}

void GLAPI glColor4dv( const GLdouble *v)
{
    (*__gl_dispatch.dispatch.Color4dv)(v);
}

void GLAPI glColor4f( GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha)
{
    (*__gl_dispatch.dispatch.Color4f)(red, green, blue, alpha);
}

void GLAPI glColor4fv( const GLfloat *v)
{
    (*__gl_dispatch.dispatch.Color4fv)(v);
}

void GLAPI glColor4i( GLint red, GLint green, GLint blue, GLint alpha)
{
    (*__gl_dispatch.dispatch.Color4i)(red, green, blue, alpha);
}

void GLAPI glColor4iv( const GLint *v)
{
    (*__gl_dispatch.dispatch.Color4iv)(v);
}

void GLAPI glColor4s( GLshort red, GLshort green, GLshort blue, GLshort alpha)
{
    (*__gl_dispatch.dispatch.Color4s)(red, green, blue, alpha);
}

void GLAPI glColor4sv( const GLshort *v)
{
    (*__gl_dispatch.dispatch.Color4sv)(v);
}

void GLAPI glColor4ub( GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha)
{
    (*__gl_dispatch.dispatch.Color4ub)(red, green, blue, alpha);
}

void GLAPI glColor4ubv( const GLubyte *v)
{
    (*__gl_dispatch.dispatch.Color4ubv)(v);
}

void GLAPI glColor4ui( GLuint red, GLuint green, GLuint blue, GLuint alpha)
{
    (*__gl_dispatch.dispatch.Color4ui)(red, green, blue, alpha);
}

void GLAPI glColor4uiv( const GLuint *v)
{
    (*__gl_dispatch.dispatch.Color4uiv)(v);
}

void GLAPI glColor4us( GLushort red, GLushort green, GLushort blue, GLushort alpha)
{
    (*__gl_dispatch.dispatch.Color4us)(red, green, blue, alpha);
}

void GLAPI glColor4usv( const GLushort *v)
{
    (*__gl_dispatch.dispatch.Color4usv)(v);
}

void GLAPI glEdgeFlag( GLboolean flag)
{
    (*__gl_dispatch.dispatch.EdgeFlag)(flag);
}

void GLAPI glEdgeFlagv( const GLboolean *flag)
{
    (*__gl_dispatch.dispatch.EdgeFlagv)(flag);
}

void GLAPI glEnd( void)
{
    (*__gl_dispatch.dispatch.End)();
}

void GLAPI glIndexd( GLdouble c)
{
    (*__gl_dispatch.dispatch.Indexd)(c);
}

void GLAPI glIndexdv( const GLdouble *c)
{
    (*__gl_dispatch.dispatch.Indexdv)(c);
}

void GLAPI glIndexf( GLfloat c)
{
    (*__gl_dispatch.dispatch.Indexf)(c);
}

void GLAPI glIndexfv( const GLfloat *c)
{
    (*__gl_dispatch.dispatch.Indexfv)(c);
}

void GLAPI glIndexi( GLint c)
{
    (*__gl_dispatch.dispatch.Indexi)(c);
}

void GLAPI glIndexiv( const GLint *c)
{
    (*__gl_dispatch.dispatch.Indexiv)(c);
}

void GLAPI glIndexs( GLshort c)
{
    (*__gl_dispatch.dispatch.Indexs)(c);
}

void GLAPI glIndexsv( const GLshort *c)
{
    (*__gl_dispatch.dispatch.Indexsv)(c);
}

void GLAPI glNormal3b( GLbyte nx, GLbyte ny, GLbyte nz)
{
    (*__gl_dispatch.dispatch.Normal3b)(nx, ny, nz);
}

void GLAPI glNormal3bv( const GLbyte *v)
{
    (*__gl_dispatch.dispatch.Normal3bv)(v);
}

void GLAPI glNormal3d( GLdouble nx, GLdouble ny, GLdouble nz)
{
    (*__gl_dispatch.dispatch.Normal3d)(nx, ny, nz);
}

void GLAPI glNormal3dv( const GLdouble *v)
{
    (*__gl_dispatch.dispatch.Normal3dv)(v);
}

void GLAPI glNormal3f( GLfloat nx, GLfloat ny, GLfloat nz)
{
    (*__gl_dispatch.dispatch.Normal3f)(nx, ny, nz);
}

void GLAPI glNormal3fv( const GLfloat *v)
{
    (*__gl_dispatch.dispatch.Normal3fv)(v);
}

void GLAPI glNormal3i( GLint nx, GLint ny, GLint nz)
{
    (*__gl_dispatch.dispatch.Normal3i)(nx, ny, nz);
}

void GLAPI glNormal3iv( const GLint *v)
{
    (*__gl_dispatch.dispatch.Normal3iv)(v);
}

void GLAPI glNormal3s( GLshort nx, GLshort ny, GLshort nz)
{
    (*__gl_dispatch.dispatch.Normal3s)(nx, ny, nz);
}

void GLAPI glNormal3sv( const GLshort *v)
{
    (*__gl_dispatch.dispatch.Normal3sv)(v);
}

void GLAPI glRasterPos2d( GLdouble x, GLdouble y)
{
    (*__gl_dispatch.dispatch.RasterPos2d)(x, y);
}

void GLAPI glRasterPos2dv( const GLdouble *v)
{
    (*__gl_dispatch.dispatch.RasterPos2dv)(v);
}

void GLAPI glRasterPos2f( GLfloat x, GLfloat y)
{
    (*__gl_dispatch.dispatch.RasterPos2f)(x, y);
}

void GLAPI glRasterPos2fv( const GLfloat *v)
{
    (*__gl_dispatch.dispatch.RasterPos2fv)(v);
}

void GLAPI glRasterPos2i( GLint x, GLint y)
{
    (*__gl_dispatch.dispatch.RasterPos2i)(x, y);
}

void GLAPI glRasterPos2iv( const GLint *v)
{
    (*__gl_dispatch.dispatch.RasterPos2iv)(v);
}

void GLAPI glRasterPos2s( GLshort x, GLshort y)
{
    (*__gl_dispatch.dispatch.RasterPos2s)(x, y);
}

void GLAPI glRasterPos2sv( const GLshort *v)
{
    (*__gl_dispatch.dispatch.RasterPos2sv)(v);
}

void GLAPI glRasterPos3d( GLdouble x, GLdouble y, GLdouble z)
{
    (*__gl_dispatch.dispatch.RasterPos3d)(x, y, z);
}

void GLAPI glRasterPos3dv( const GLdouble *v)
{
    (*__gl_dispatch.dispatch.RasterPos3dv)(v);
}

void GLAPI glRasterPos3f( GLfloat x, GLfloat y, GLfloat z)
{
    (*__gl_dispatch.dispatch.RasterPos3f)(x, y, z);
}

void GLAPI glRasterPos3fv( const GLfloat *v)
{
    (*__gl_dispatch.dispatch.RasterPos3fv)(v);
}

void GLAPI glRasterPos3i( GLint x, GLint y, GLint z)
{
    (*__gl_dispatch.dispatch.RasterPos3i)(x, y, z);
}

void GLAPI glRasterPos3iv( const GLint *v)
{
    (*__gl_dispatch.dispatch.RasterPos3iv)(v);
}

void GLAPI glRasterPos3s( GLshort x, GLshort y, GLshort z)
{
    (*__gl_dispatch.dispatch.RasterPos3s)(x, y, z);
}

void GLAPI glRasterPos3sv( const GLshort *v)
{
    (*__gl_dispatch.dispatch.RasterPos3sv)(v);
}

void GLAPI glRasterPos4d( GLdouble x, GLdouble y, GLdouble z, GLdouble w)
{
    (*__gl_dispatch.dispatch.RasterPos4d)(x, y, z, w);
}

void GLAPI glRasterPos4dv( const GLdouble *v)
{
    (*__gl_dispatch.dispatch.RasterPos4dv)(v);
}

void GLAPI glRasterPos4f( GLfloat x, GLfloat y, GLfloat z, GLfloat w)
{
    (*__gl_dispatch.dispatch.RasterPos4f)(x, y, z, w);
}

void GLAPI glRasterPos4fv( const GLfloat *v)
{
    (*__gl_dispatch.dispatch.RasterPos4fv)(v);
}

void GLAPI glRasterPos4i( GLint x, GLint y, GLint z, GLint w)
{
    (*__gl_dispatch.dispatch.RasterPos4i)(x, y, z, w);
}

void GLAPI glRasterPos4iv( const GLint *v)
{
    (*__gl_dispatch.dispatch.RasterPos4iv)(v);
}

void GLAPI glRasterPos4s( GLshort x, GLshort y, GLshort z, GLshort w)
{
    (*__gl_dispatch.dispatch.RasterPos4s)(x, y, z, w);
}

void GLAPI glRasterPos4sv( const GLshort *v)
{
    (*__gl_dispatch.dispatch.RasterPos4sv)(v);
}

void GLAPI glRectd( GLdouble x1, GLdouble y1, GLdouble x2, GLdouble y2)
{
    (*__gl_dispatch.dispatch.Rectd)(x1, y1, x2, y2);
}

void GLAPI glRectdv( const GLdouble *v1, const GLdouble *v2)
{
    (*__gl_dispatch.dispatch.Rectdv)(v1, v2);
}

void GLAPI glRectf( GLfloat x1, GLfloat y1, GLfloat x2, GLfloat y2)
{
    (*__gl_dispatch.dispatch.Rectf)(x1, y1, x2, y2);
}

void GLAPI glRectfv( const GLfloat *v1, const GLfloat *v2)
{
    (*__gl_dispatch.dispatch.Rectfv)(v1, v2);
}

void GLAPI glRecti( GLint x1, GLint y1, GLint x2, GLint y2)
{
    (*__gl_dispatch.dispatch.Recti)(x1, y1, x2, y2);
}

void GLAPI glRectiv( const GLint *v1, const GLint *v2)
{
    (*__gl_dispatch.dispatch.Rectiv)(v1, v2);
}

void GLAPI glRects( GLshort x1, GLshort y1, GLshort x2, GLshort y2)
{
    (*__gl_dispatch.dispatch.Rects)(x1, y1, x2, y2);
}

void GLAPI glRectsv( const GLshort *v1, const GLshort *v2)
{
    (*__gl_dispatch.dispatch.Rectsv)(v1, v2);
}

void GLAPI glTexCoord1d( GLdouble s)
{
    (*__gl_dispatch.dispatch.TexCoord1d)(s);
}

void GLAPI glTexCoord1dv( const GLdouble *v)
{
    (*__gl_dispatch.dispatch.TexCoord1dv)(v);
}

void GLAPI glTexCoord1f( GLfloat s)
{
    (*__gl_dispatch.dispatch.TexCoord1f)(s);
}

void GLAPI glTexCoord1fv( const GLfloat *v)
{
    (*__gl_dispatch.dispatch.TexCoord1fv)(v);
}

void GLAPI glTexCoord1i( GLint s)
{
    (*__gl_dispatch.dispatch.TexCoord1i)(s);
}

void GLAPI glTexCoord1iv( const GLint *v)
{
    (*__gl_dispatch.dispatch.TexCoord1iv)(v);
}

void GLAPI glTexCoord1s( GLshort s)
{
    (*__gl_dispatch.dispatch.TexCoord1s)(s);
}

void GLAPI glTexCoord1sv( const GLshort *v)
{
    (*__gl_dispatch.dispatch.TexCoord1sv)(v);
}

void GLAPI glTexCoord2d( GLdouble s, GLdouble t)
{
    (*__gl_dispatch.dispatch.TexCoord2d)(s, t);
}

void GLAPI glTexCoord2dv( const GLdouble *v)
{
    (*__gl_dispatch.dispatch.TexCoord2dv)(v);
}

void GLAPI glTexCoord2f( GLfloat s, GLfloat t)
{
    (*__gl_dispatch.dispatch.TexCoord2f)(s, t);
}

void GLAPI glTexCoord2fv( const GLfloat *v)
{
    (*__gl_dispatch.dispatch.TexCoord2fv)(v);
}

void GLAPI glTexCoord2i( GLint s, GLint t)
{
    (*__gl_dispatch.dispatch.TexCoord2i)(s, t);
}

void GLAPI glTexCoord2iv( const GLint *v)
{
    (*__gl_dispatch.dispatch.TexCoord2iv)(v);
}

void GLAPI glTexCoord2s( GLshort s, GLshort t)
{
    (*__gl_dispatch.dispatch.TexCoord2s)(s, t);
}

void GLAPI glTexCoord2sv( const GLshort *v)
{
    (*__gl_dispatch.dispatch.TexCoord2sv)(v);
}

void GLAPI glTexCoord3d( GLdouble s, GLdouble t, GLdouble r)
{
    (*__gl_dispatch.dispatch.TexCoord3d)(s, t, r);
}

void GLAPI glTexCoord3dv( const GLdouble *v)
{
    (*__gl_dispatch.dispatch.TexCoord3dv)(v);
}

void GLAPI glTexCoord3f( GLfloat s, GLfloat t, GLfloat r)
{
    (*__gl_dispatch.dispatch.TexCoord3f)(s, t, r);
}

void GLAPI glTexCoord3fv( const GLfloat *v)
{
    (*__gl_dispatch.dispatch.TexCoord3fv)(v);
}

void GLAPI glTexCoord3i( GLint s, GLint t, GLint r)
{
    (*__gl_dispatch.dispatch.TexCoord3i)(s, t, r);
}

void GLAPI glTexCoord3iv( const GLint *v)
{
    (*__gl_dispatch.dispatch.TexCoord3iv)(v);
}

void GLAPI glTexCoord3s( GLshort s, GLshort t, GLshort r)
{
    (*__gl_dispatch.dispatch.TexCoord3s)(s, t, r);
}

void GLAPI glTexCoord3sv( const GLshort *v)
{
    (*__gl_dispatch.dispatch.TexCoord3sv)(v);
}

void GLAPI glTexCoord4d( GLdouble s, GLdouble t, GLdouble r, GLdouble q)
{
    (*__gl_dispatch.dispatch.TexCoord4d)(s, t, r, q);
}

void GLAPI glTexCoord4dv( const GLdouble *v)
{
    (*__gl_dispatch.dispatch.TexCoord4dv)(v);
}

void GLAPI glTexCoord4f( GLfloat s, GLfloat t, GLfloat r, GLfloat q)
{
    (*__gl_dispatch.dispatch.TexCoord4f)(s, t, r, q);
}

void GLAPI glTexCoord4fv( const GLfloat *v)
{
    (*__gl_dispatch.dispatch.TexCoord4fv)(v);
}

void GLAPI glTexCoord4i( GLint s, GLint t, GLint r, GLint q)
{
    (*__gl_dispatch.dispatch.TexCoord4i)(s, t, r, q);
}

void GLAPI glTexCoord4iv( const GLint *v)
{
    (*__gl_dispatch.dispatch.TexCoord4iv)(v);
}

void GLAPI glTexCoord4s( GLshort s, GLshort t, GLshort r, GLshort q)
{
    (*__gl_dispatch.dispatch.TexCoord4s)(s, t, r, q);
}

void GLAPI glTexCoord4sv( const GLshort *v)
{
    (*__gl_dispatch.dispatch.TexCoord4sv)(v);
}

void GLAPI glVertex2d( GLdouble x, GLdouble y)
{
    (*__gl_dispatch.dispatch.Vertex2d)(x, y);
}

void GLAPI glVertex2dv( const GLdouble *v)
{
    (*__gl_dispatch.dispatch.Vertex2dv)(v);
}

void GLAPI glVertex2f( GLfloat x, GLfloat y)
{
    (*__gl_dispatch.dispatch.Vertex2f)(x, y);
}

void GLAPI glVertex2fv( const GLfloat *v)
{
    (*__gl_dispatch.dispatch.Vertex2fv)(v);
}

void GLAPI glVertex2i( GLint x, GLint y)
{
    (*__gl_dispatch.dispatch.Vertex2i)(x, y);
}

void GLAPI glVertex2iv( const GLint *v)
{
    (*__gl_dispatch.dispatch.Vertex2iv)(v);
}

void GLAPI glVertex2s( GLshort x, GLshort y)
{
    (*__gl_dispatch.dispatch.Vertex2s)(x, y);
}

void GLAPI glVertex2sv( const GLshort *v)
{
    (*__gl_dispatch.dispatch.Vertex2sv)(v);
}

void GLAPI glVertex3d( GLdouble x, GLdouble y, GLdouble z)
{
    (*__gl_dispatch.dispatch.Vertex3d)(x, y, z);
}

void GLAPI glVertex3dv( const GLdouble *v)
{
    (*__gl_dispatch.dispatch.Vertex3dv)(v);
}

void GLAPI glVertex3f( GLfloat x, GLfloat y, GLfloat z)
{
    (*__gl_dispatch.dispatch.Vertex3f)(x, y, z);
}

void GLAPI glVertex3fv( const GLfloat *v)
{
    (*__gl_dispatch.dispatch.Vertex3fv)(v);
}

void GLAPI glVertex3i( GLint x, GLint y, GLint z)
{
    (*__gl_dispatch.dispatch.Vertex3i)(x, y, z);
}

void GLAPI glVertex3iv( const GLint *v)
{
    (*__gl_dispatch.dispatch.Vertex3iv)(v);
}

void GLAPI glVertex3s( GLshort x, GLshort y, GLshort z)
{
    (*__gl_dispatch.dispatch.Vertex3s)(x, y, z);
}

void GLAPI glVertex3sv( const GLshort *v)
{
    (*__gl_dispatch.dispatch.Vertex3sv)(v);
}

void GLAPI glVertex4d( GLdouble x, GLdouble y, GLdouble z, GLdouble w)
{
    (*__gl_dispatch.dispatch.Vertex4d)(x, y, z, w);
}

void GLAPI glVertex4dv( const GLdouble *v)
{
    (*__gl_dispatch.dispatch.Vertex4dv)(v);
}

void GLAPI glVertex4f( GLfloat x, GLfloat y, GLfloat z, GLfloat w)
{
    (*__gl_dispatch.dispatch.Vertex4f)(x, y, z, w);
}

void GLAPI glVertex4fv( const GLfloat *v)
{
    (*__gl_dispatch.dispatch.Vertex4fv)(v);
}

void GLAPI glVertex4i( GLint x, GLint y, GLint z, GLint w)
{
    (*__gl_dispatch.dispatch.Vertex4i)(x, y, z, w);
}

void GLAPI glVertex4iv( const GLint *v)
{
    (*__gl_dispatch.dispatch.Vertex4iv)(v);
}

void GLAPI glVertex4s( GLshort x, GLshort y, GLshort z, GLshort w)
{
    (*__gl_dispatch.dispatch.Vertex4s)(x, y, z, w);
}

void GLAPI glVertex4sv( const GLshort *v)
{
    (*__gl_dispatch.dispatch.Vertex4sv)(v);
}

void GLAPI glClipPlane( GLenum plane, const GLdouble *equation)
{
    (*__gl_dispatch.dispatch.ClipPlane)(plane, equation);
}

void GLAPI glColorMaterial( GLenum face, GLenum mode)
{
    (*__gl_dispatch.dispatch.ColorMaterial)(face, mode);
}

void GLAPI glCullFace( GLenum mode)
{
    (*__gl_dispatch.dispatch.CullFace)(mode);
}

void GLAPI glFogf( GLenum pname, GLfloat param)
{
    (*__gl_dispatch.dispatch.Fogf)(pname, param);
}

void GLAPI glFogfv( GLenum pname, const GLfloat *params)
{
    (*__gl_dispatch.dispatch.Fogfv)(pname, params);
}

void GLAPI glFogi( GLenum pname, GLint param)
{
    (*__gl_dispatch.dispatch.Fogi)(pname, param);
}

void GLAPI glFogiv( GLenum pname, const GLint *params)
{
    (*__gl_dispatch.dispatch.Fogiv)(pname, params);
}

void GLAPI glFrontFace( GLenum mode)
{
    (*__gl_dispatch.dispatch.FrontFace)(mode);
}

void GLAPI glHint( GLenum target, GLenum mode)
{
    (*__gl_dispatch.dispatch.Hint)(target, mode);
}

void GLAPI glLightf( GLenum light, GLenum pname, GLfloat param)
{
    (*__gl_dispatch.dispatch.Lightf)(light, pname, param);
}

void GLAPI glLightfv( GLenum light, GLenum pname, const GLfloat *params)
{
    (*__gl_dispatch.dispatch.Lightfv)(light, pname, params);
}

void GLAPI glLighti( GLenum light, GLenum pname, GLint param)
{
    (*__gl_dispatch.dispatch.Lighti)(light, pname, param);
}

void GLAPI glLightiv( GLenum light, GLenum pname, const GLint *params)
{
    (*__gl_dispatch.dispatch.Lightiv)(light, pname, params);
}

void GLAPI glLightModelf( GLenum pname, GLfloat param)
{
    (*__gl_dispatch.dispatch.LightModelf)(pname, param);
}

void GLAPI glLightModelfv( GLenum pname, const GLfloat *params)
{
    (*__gl_dispatch.dispatch.LightModelfv)(pname, params);
}

void GLAPI glLightModeli( GLenum pname, GLint param)
{
    (*__gl_dispatch.dispatch.LightModeli)(pname, param);
}

void GLAPI glLightModeliv( GLenum pname, const GLint *params)
{
    (*__gl_dispatch.dispatch.LightModeliv)(pname, params);
}

void GLAPI glLineStipple( GLint factor, GLushort pattern)
{
    (*__gl_dispatch.dispatch.LineStipple)(factor, pattern);
}

void GLAPI glLineWidth( GLfloat width)
{
    (*__gl_dispatch.dispatch.LineWidth)(width);
}

void GLAPI glMaterialf( GLenum face, GLenum pname, GLfloat param)
{
    (*__gl_dispatch.dispatch.Materialf)(face, pname, param);
}

void GLAPI glMaterialfv( GLenum face, GLenum pname, const GLfloat *params)
{
    (*__gl_dispatch.dispatch.Materialfv)(face, pname, params);
}

void GLAPI glMateriali( GLenum face, GLenum pname, GLint param)
{
    (*__gl_dispatch.dispatch.Materiali)(face, pname, param);
}

void GLAPI glMaterialiv( GLenum face, GLenum pname, const GLint *params)
{
    (*__gl_dispatch.dispatch.Materialiv)(face, pname, params);
}

void GLAPI glPointSize( GLfloat size)
{
    (*__gl_dispatch.dispatch.PointSize)(size);
}

void GLAPI glPolygonMode( GLenum face, GLenum mode)
{
    (*__gl_dispatch.dispatch.PolygonMode)(face, mode);
}

void GLAPI glPolygonStipple( const GLubyte *mask)
{
    (*__gl_dispatch.dispatch.PolygonStipple)(mask);
}

void GLAPI glScissor( GLint x, GLint y, GLsizei width, GLsizei height)
{
    (*__gl_dispatch.dispatch.Scissor)(x, y, width, height);
}

void GLAPI glShadeModel( GLenum mode)
{
    (*__gl_dispatch.dispatch.ShadeModel)(mode);
}

void GLAPI glTexParameterf( GLenum target, GLenum pname, GLfloat param)
{
    (*__gl_dispatch.dispatch.TexParameterf)(target, pname, param);
}

void GLAPI glTexParameterfv( GLenum target, GLenum pname, const GLfloat *params)
{
    (*__gl_dispatch.dispatch.TexParameterfv)(target, pname, params);
}

void GLAPI glTexParameteri( GLenum target, GLenum pname, GLint param)
{
    (*__gl_dispatch.dispatch.TexParameteri)(target, pname, param);
}

void GLAPI glTexParameteriv( GLenum target, GLenum pname, const GLint *params)
{
    (*__gl_dispatch.dispatch.TexParameteriv)(target, pname, params);
}

void GLAPI glTexImage1D( GLenum target, GLint level, GLint internalformat, GLsizei width, GLint border, GLenum format, GLenum type, const GLvoid *pixels)
{
    (*__gl_dispatch.dispatch.TexImage1D)(target, level, internalformat, width, border, format, type, pixels);
}

void GLAPI glTexImage2D( GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels)
{
    (*__gl_dispatch.dispatch.TexImage2D)(target, level, internalformat, width, height, border, format, type, pixels);
}

void GLAPI glTexEnvf( GLenum target, GLenum pname, GLfloat param)
{
    (*__gl_dispatch.dispatch.TexEnvf)(target, pname, param);
}

void GLAPI glTexEnvfv( GLenum target, GLenum pname, const GLfloat *params)
{
    (*__gl_dispatch.dispatch.TexEnvfv)(target, pname, params);
}

void GLAPI glTexEnvi( GLenum target, GLenum pname, GLint param)
{
    (*__gl_dispatch.dispatch.TexEnvi)(target, pname, param);
}

void GLAPI glTexEnviv( GLenum target, GLenum pname, const GLint *params)
{
    (*__gl_dispatch.dispatch.TexEnviv)(target, pname, params);
}

void GLAPI glTexGend( GLenum coord, GLenum pname, GLdouble param)
{
    (*__gl_dispatch.dispatch.TexGend)(coord, pname, param);
}

void GLAPI glTexGendv( GLenum coord, GLenum pname, const GLdouble *params)
{
    (*__gl_dispatch.dispatch.TexGendv)(coord, pname, params);
}

void GLAPI glTexGenf( GLenum coord, GLenum pname, GLfloat param)
{
    (*__gl_dispatch.dispatch.TexGenf)(coord, pname, param);
}

void GLAPI glTexGenfv( GLenum coord, GLenum pname, const GLfloat *params)
{
    (*__gl_dispatch.dispatch.TexGenfv)(coord, pname, params);
}

void GLAPI glTexGeni( GLenum coord, GLenum pname, GLint param)
{
    (*__gl_dispatch.dispatch.TexGeni)(coord, pname, param);
}

void GLAPI glTexGeniv( GLenum coord, GLenum pname, const GLint *params)
{
    (*__gl_dispatch.dispatch.TexGeniv)(coord, pname, params);
}

void GLAPI glFeedbackBuffer( GLsizei size, GLenum type, GLfloat *buffer)
{
    (*__gl_dispatch.dispatch.FeedbackBuffer)(size, type, buffer);
}

void GLAPI glSelectBuffer( GLsizei size, GLuint *buffer)
{
    (*__gl_dispatch.dispatch.SelectBuffer)(size, buffer);
}

GLint GLAPI glRenderMode( GLenum mode)
{
    return (*__gl_dispatch.dispatch.RenderMode)(mode);
}

void GLAPI glInitNames( void)
{
    (*__gl_dispatch.dispatch.InitNames)();
}

void GLAPI glLoadName( GLuint name)
{
    (*__gl_dispatch.dispatch.LoadName)(name);
}

void GLAPI glPassThrough( GLfloat token)
{
    (*__gl_dispatch.dispatch.PassThrough)(token);
}

void GLAPI glPopName( void)
{
    (*__gl_dispatch.dispatch.PopName)();
}

void GLAPI glPushName( GLuint name)
{
    (*__gl_dispatch.dispatch.PushName)(name);
}

void GLAPI glDrawBuffer( GLenum mode)
{
    (*__gl_dispatch.dispatch.DrawBuffer)(mode);
}

void GLAPI glClear( GLbitfield mask)
{
    (*__gl_dispatch.dispatch.Clear)(mask);
}

void GLAPI glClearAccum( GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha)
{
    (*__gl_dispatch.dispatch.ClearAccum)(red, green, blue, alpha);
}

void GLAPI glClearIndex( GLfloat c)
{
    (*__gl_dispatch.dispatch.ClearIndex)(c);
}

void GLAPI glClearColor( GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
{
    (*__gl_dispatch.dispatch.ClearColor)(red, green, blue, alpha);
}

void GLAPI glClearStencil( GLint s)
{
    (*__gl_dispatch.dispatch.ClearStencil)(s);
}

void GLAPI glClearDepth( GLclampd depth)
{
    (*__gl_dispatch.dispatch.ClearDepth)(depth);
}

void GLAPI glStencilMask( GLuint mask)
{
    (*__gl_dispatch.dispatch.StencilMask)(mask);
}

void GLAPI glColorMask( GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha)
{
    (*__gl_dispatch.dispatch.ColorMask)(red, green, blue, alpha);
}

void GLAPI glDepthMask( GLboolean flag)
{
    (*__gl_dispatch.dispatch.DepthMask)(flag);
}

void GLAPI glIndexMask( GLuint mask)
{
    (*__gl_dispatch.dispatch.IndexMask)(mask);
}

void GLAPI glAccum( GLenum op, GLfloat value)
{
    (*__gl_dispatch.dispatch.Accum)(op, value);
}

void GLAPI glDisable( GLenum cap)
{
    (*__gl_dispatch.dispatch.Disable)(cap);
}

void GLAPI glEnable( GLenum cap)
{
    (*__gl_dispatch.dispatch.Enable)(cap);
}

void GLAPI glFinish( void)
{
    (*__gl_dispatch.dispatch.Finish)();
}

void GLAPI glFlush( void)
{
    (*__gl_dispatch.dispatch.Flush)();
}

void GLAPI glPopAttrib( void)
{
    (*__gl_dispatch.dispatch.PopAttrib)();
}

void GLAPI glPushAttrib( GLbitfield mask)
{
    (*__gl_dispatch.dispatch.PushAttrib)(mask);
}

void GLAPI glMap1d( GLenum target, GLdouble u1, GLdouble u2, GLint stride, GLint order, const GLdouble *points)
{
    (*__gl_dispatch.dispatch.Map1d)(target, u1, u2, stride, order, points);
}

void GLAPI glMap1f( GLenum target, GLfloat u1, GLfloat u2, GLint stride, GLint order, const GLfloat *points)
{
    (*__gl_dispatch.dispatch.Map1f)(target, u1, u2, stride, order, points);
}

void GLAPI glMap2d( GLenum target, GLdouble u1, GLdouble u2, GLint ustride, GLint uorder, GLdouble v1, GLdouble v2, GLint vstride, GLint vorder, const GLdouble *points)
{
    (*__gl_dispatch.dispatch.Map2d)(target, u1, u2, ustride, uorder, v1, v2, vstride, vorder, points);
}

void GLAPI glMap2f( GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2, GLint vstride, GLint vorder, const GLfloat *points)
{
    (*__gl_dispatch.dispatch.Map2f)(target, u1, u2, ustride, uorder, v1, v2, vstride, vorder, points);
}

void GLAPI glMapGrid1d( GLint un, GLdouble u1, GLdouble u2)
{
    (*__gl_dispatch.dispatch.MapGrid1d)(un, u1, u2);
}

void GLAPI glMapGrid1f( GLint un, GLfloat u1, GLfloat u2)
{
    (*__gl_dispatch.dispatch.MapGrid1f)(un, u1, u2);
}

void GLAPI glMapGrid2d( GLint un, GLdouble u1, GLdouble u2, GLint vn, GLdouble v1, GLdouble v2)
{
    (*__gl_dispatch.dispatch.MapGrid2d)(un, u1, u2, vn, v1, v2);
}

void GLAPI glMapGrid2f( GLint un, GLfloat u1, GLfloat u2, GLint vn, GLfloat v1, GLfloat v2)
{
    (*__gl_dispatch.dispatch.MapGrid2f)(un, u1, u2, vn, v1, v2);
}

void GLAPI glEvalCoord1d( GLdouble u)
{
    (*__gl_dispatch.dispatch.EvalCoord1d)(u);
}

void GLAPI glEvalCoord1dv( const GLdouble *u)
{
    (*__gl_dispatch.dispatch.EvalCoord1dv)(u);
}

void GLAPI glEvalCoord1f( GLfloat u)
{
    (*__gl_dispatch.dispatch.EvalCoord1f)(u);
}

void GLAPI glEvalCoord1fv( const GLfloat *u)
{
    (*__gl_dispatch.dispatch.EvalCoord1fv)(u);
}

void GLAPI glEvalCoord2d( GLdouble u, GLdouble v)
{
    (*__gl_dispatch.dispatch.EvalCoord2d)(u, v);
}

void GLAPI glEvalCoord2dv( const GLdouble *u)
{
    (*__gl_dispatch.dispatch.EvalCoord2dv)(u);
}

void GLAPI glEvalCoord2f( GLfloat u, GLfloat v)
{
    (*__gl_dispatch.dispatch.EvalCoord2f)(u, v);
}

void GLAPI glEvalCoord2fv( const GLfloat *u)
{
    (*__gl_dispatch.dispatch.EvalCoord2fv)(u);
}

void GLAPI glEvalMesh1( GLenum mode, GLint i1, GLint i2)
{
    (*__gl_dispatch.dispatch.EvalMesh1)(mode, i1, i2);
}

void GLAPI glEvalPoint1( GLint i)
{
    (*__gl_dispatch.dispatch.EvalPoint1)(i);
}

void GLAPI glEvalMesh2( GLenum mode, GLint i1, GLint i2, GLint j1, GLint j2)
{
    (*__gl_dispatch.dispatch.EvalMesh2)(mode, i1, i2, j1, j2);
}

void GLAPI glEvalPoint2( GLint i, GLint j)
{
    (*__gl_dispatch.dispatch.EvalPoint2)(i, j);
}

void GLAPI glAlphaFunc( GLenum func, GLclampf ref)
{
    (*__gl_dispatch.dispatch.AlphaFunc)(func, ref);
}

void GLAPI glBlendFunc( GLenum sfactor, GLenum dfactor)
{
    (*__gl_dispatch.dispatch.BlendFunc)(sfactor, dfactor);
}

void GLAPI glLogicOp( GLenum opcode)
{
    (*__gl_dispatch.dispatch.LogicOp)(opcode);
}

void GLAPI glStencilFunc( GLenum func, GLint ref, GLuint mask)
{
    (*__gl_dispatch.dispatch.StencilFunc)(func, ref, mask);
}

void GLAPI glStencilOp( GLenum fail, GLenum zfail, GLenum zpass)
{
    (*__gl_dispatch.dispatch.StencilOp)(fail, zfail, zpass);
}

void GLAPI glDepthFunc( GLenum func)
{
    (*__gl_dispatch.dispatch.DepthFunc)(func);
}

void GLAPI glPixelZoom( GLfloat xfactor, GLfloat yfactor)
{
    (*__gl_dispatch.dispatch.PixelZoom)(xfactor, yfactor);
}

void GLAPI glPixelTransferf( GLenum pname, GLfloat param)
{
    (*__gl_dispatch.dispatch.PixelTransferf)(pname, param);
}

void GLAPI glPixelTransferi( GLenum pname, GLint param)
{
    (*__gl_dispatch.dispatch.PixelTransferi)(pname, param);
}

void GLAPI glPixelStoref( GLenum pname, GLfloat param)
{
    (*__gl_dispatch.dispatch.PixelStoref)(pname, param);
}

void GLAPI glPixelStorei( GLenum pname, GLint param)
{
    (*__gl_dispatch.dispatch.PixelStorei)(pname, param);
}

void GLAPI glPixelMapfv( GLenum map, GLint mapsize, const GLfloat *values)
{
    (*__gl_dispatch.dispatch.PixelMapfv)(map, mapsize, values);
}

void GLAPI glPixelMapuiv( GLenum map, GLint mapsize, const GLuint *values)
{
    (*__gl_dispatch.dispatch.PixelMapuiv)(map, mapsize, values);
}

void GLAPI glPixelMapusv( GLenum map, GLint mapsize, const GLushort *values)
{
    (*__gl_dispatch.dispatch.PixelMapusv)(map, mapsize, values);
}

void GLAPI glReadBuffer( GLenum mode)
{
    (*__gl_dispatch.dispatch.ReadBuffer)(mode);
}

void GLAPI glCopyPixels( GLint x, GLint y, GLsizei width, GLsizei height, GLenum type)
{
    (*__gl_dispatch.dispatch.CopyPixels)(x, y, width, height, type);
}

void GLAPI glReadPixels( GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels)
{
    (*__gl_dispatch.dispatch.ReadPixels)(x, y, width, height, format, type, pixels);
}

void GLAPI glDrawPixels( GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels)
{
    (*__gl_dispatch.dispatch.DrawPixels)(width, height, format, type, pixels);
}

void GLAPI glGetBooleanv( GLenum pname, GLboolean *params)
{
    (*__gl_dispatch.dispatch.GetBooleanv)(pname, params);
}

void GLAPI glGetClipPlane( GLenum plane, GLdouble *equation)
{
    (*__gl_dispatch.dispatch.GetClipPlane)(plane, equation);
}

void GLAPI glGetDoublev( GLenum pname, GLdouble *params)
{
    (*__gl_dispatch.dispatch.GetDoublev)(pname, params);
}

GLenum GLAPI glGetError( void)
{
    return (*__gl_dispatch.dispatch.GetError)();
}

void GLAPI glGetFloatv( GLenum pname, GLfloat *params)
{
    (*__gl_dispatch.dispatch.GetFloatv)(pname, params);
}

void GLAPI glGetIntegerv( GLenum pname, GLint *params)
{
    (*__gl_dispatch.dispatch.GetIntegerv)(pname, params);
}

void GLAPI glGetLightfv( GLenum light, GLenum pname, GLfloat *params)
{
    (*__gl_dispatch.dispatch.GetLightfv)(light, pname, params);
}

void GLAPI glGetLightiv( GLenum light, GLenum pname, GLint *params)
{
    (*__gl_dispatch.dispatch.GetLightiv)(light, pname, params);
}

void GLAPI glGetMapdv( GLenum target, GLenum query, GLdouble *v)
{
    (*__gl_dispatch.dispatch.GetMapdv)(target, query, v);
}

void GLAPI glGetMapfv( GLenum target, GLenum query, GLfloat *v)
{
    (*__gl_dispatch.dispatch.GetMapfv)(target, query, v);
}

void GLAPI glGetMapiv( GLenum target, GLenum query, GLint *v)
{
    (*__gl_dispatch.dispatch.GetMapiv)(target, query, v);
}

void GLAPI glGetMaterialfv( GLenum face, GLenum pname, GLfloat *params)
{
    (*__gl_dispatch.dispatch.GetMaterialfv)(face, pname, params);
}

void GLAPI glGetMaterialiv( GLenum face, GLenum pname, GLint *params)
{
    (*__gl_dispatch.dispatch.GetMaterialiv)(face, pname, params);
}

void GLAPI glGetPixelMapfv( GLenum map, GLfloat *values)
{
    (*__gl_dispatch.dispatch.GetPixelMapfv)(map, values);
}

void GLAPI glGetPixelMapuiv( GLenum map, GLuint *values)
{
    (*__gl_dispatch.dispatch.GetPixelMapuiv)(map, values);
}

void GLAPI glGetPixelMapusv( GLenum map, GLushort *values)
{
    (*__gl_dispatch.dispatch.GetPixelMapusv)(map, values);
}

void GLAPI glGetPolygonStipple( GLubyte *mask)
{
    (*__gl_dispatch.dispatch.GetPolygonStipple)(mask);
}

const GLubyte * GLAPI glGetString( GLenum name)
{
    return (*__gl_dispatch.dispatch.GetString)(name);
}

void GLAPI glGetTexEnvfv( GLenum target, GLenum pname, GLfloat *params)
{
    (*__gl_dispatch.dispatch.GetTexEnvfv)(target, pname, params);
}

void GLAPI glGetTexEnviv( GLenum target, GLenum pname, GLint *params)
{
    (*__gl_dispatch.dispatch.GetTexEnviv)(target, pname, params);
}

void GLAPI glGetTexGendv( GLenum coord, GLenum pname, GLdouble *params)
{
    (*__gl_dispatch.dispatch.GetTexGendv)(coord, pname, params);
}

void GLAPI glGetTexGenfv( GLenum coord, GLenum pname, GLfloat *params)
{
    (*__gl_dispatch.dispatch.GetTexGenfv)(coord, pname, params);
}

void GLAPI glGetTexGeniv( GLenum coord, GLenum pname, GLint *params)
{
    (*__gl_dispatch.dispatch.GetTexGeniv)(coord, pname, params);
}

void GLAPI glGetTexImage( GLenum target, GLint level, GLenum format, GLenum type, GLvoid *pixels)
{
    (*__gl_dispatch.dispatch.GetTexImage)(target, level, format, type, pixels);
}

void GLAPI glGetTexParameterfv( GLenum target, GLenum pname, GLfloat *params)
{
    (*__gl_dispatch.dispatch.GetTexParameterfv)(target, pname, params);
}

void GLAPI glGetTexParameteriv( GLenum target, GLenum pname, GLint *params)
{
    (*__gl_dispatch.dispatch.GetTexParameteriv)(target, pname, params);
}

void GLAPI glGetTexLevelParameterfv( GLenum target, GLint level, GLenum pname, GLfloat *params)
{
    (*__gl_dispatch.dispatch.GetTexLevelParameterfv)(target, level, pname, params);
}

void GLAPI glGetTexLevelParameteriv( GLenum target, GLint level, GLenum pname, GLint *params)
{
    (*__gl_dispatch.dispatch.GetTexLevelParameteriv)(target, level, pname, params);
}

GLboolean GLAPI glIsEnabled( GLenum cap)
{
    return (*__gl_dispatch.dispatch.IsEnabled)(cap);
}

GLboolean GLAPI glIsList( GLuint list)
{
    return (*__gl_dispatch.dispatch.IsList)(list);
}

void GLAPI glDepthRange( GLclampd zNear, GLclampd zFar)
{
    (*__gl_dispatch.dispatch.DepthRange)(zNear, zFar);
}

void GLAPI glFrustum( GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar)
{
    (*__gl_dispatch.dispatch.Frustum)(left, right, bottom, top, zNear, zFar);
}

void GLAPI glLoadIdentity( void)
{
    (*__gl_dispatch.dispatch.LoadIdentity)();
}

void GLAPI glLoadMatrixf( const GLfloat *m)
{
    (*__gl_dispatch.dispatch.LoadMatrixf)(m);
}

void GLAPI glLoadMatrixd( const GLdouble *m)
{
    (*__gl_dispatch.dispatch.LoadMatrixd)(m);
}

void GLAPI glMatrixMode( GLenum mode)
{
    (*__gl_dispatch.dispatch.MatrixMode)(mode);
}

void GLAPI glMultMatrixf( const GLfloat *m)
{
    (*__gl_dispatch.dispatch.MultMatrixf)(m);
}

void GLAPI glMultMatrixd( const GLdouble *m)
{
    (*__gl_dispatch.dispatch.MultMatrixd)(m);
}

void GLAPI glOrtho( GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar)
{
    (*__gl_dispatch.dispatch.Ortho)(left, right, bottom, top, zNear, zFar);
}

void GLAPI glPopMatrix( void)
{
    (*__gl_dispatch.dispatch.PopMatrix)();
}

void GLAPI glPushMatrix( void)
{
    (*__gl_dispatch.dispatch.PushMatrix)();
}

void GLAPI glRotated( GLdouble angle, GLdouble x, GLdouble y, GLdouble z)
{
    (*__gl_dispatch.dispatch.Rotated)(angle, x, y, z);
}

void GLAPI glRotatef( GLfloat angle, GLfloat x, GLfloat y, GLfloat z)
{
    (*__gl_dispatch.dispatch.Rotatef)(angle, x, y, z);
}

void GLAPI glScaled( GLdouble x, GLdouble y, GLdouble z)
{
    (*__gl_dispatch.dispatch.Scaled)(x, y, z);
}

void GLAPI glScalef( GLfloat x, GLfloat y, GLfloat z)
{
    (*__gl_dispatch.dispatch.Scalef)(x, y, z);
}

void GLAPI glTranslated( GLdouble x, GLdouble y, GLdouble z)
{
    (*__gl_dispatch.dispatch.Translated)(x, y, z);
}

void GLAPI glTranslatef( GLfloat x, GLfloat y, GLfloat z)
{
    (*__gl_dispatch.dispatch.Translatef)(x, y, z);
}

void GLAPI glViewport( GLint x, GLint y, GLsizei width, GLsizei height)
{
    (*__gl_dispatch.dispatch.Viewport)(x, y, width, height);
}

void GLAPI glArrayElement( GLint i)
{
    (*__gl_dispatch.dispatch.ArrayElement)(i);
}

void GLAPI glColorPointer( GLint size, GLenum type, GLsizei stride, const GLvoid *pointer)
{
    (*__gl_dispatch.dispatch.ColorPointer)(size, type, stride, pointer);
}

void GLAPI glDisableClientState( GLenum array)
{
    (*__gl_dispatch.dispatch.DisableClientState)(array);
}

void GLAPI glDrawArrays( GLenum mode, GLint first, GLsizei count)
{
    (*__gl_dispatch.dispatch.DrawArrays)(mode, first, count);
}

void GLAPI glDrawElements( GLenum mode, GLsizei count, GLenum type, const GLvoid *indices)
{
    (*__gl_dispatch.dispatch.DrawElements)(mode, count, type, indices);
}

void GLAPI glEdgeFlagPointer( GLsizei stride, const GLboolean *pointer)
{
    (*__gl_dispatch.dispatch.EdgeFlagPointer)(stride, pointer);
}

void GLAPI glEnableClientState( GLenum array)
{
    (*__gl_dispatch.dispatch.EnableClientState)(array);
}

void GLAPI glGetPointerv( GLenum pname, GLvoid* *params)
{
    (*__gl_dispatch.dispatch.GetPointerv)(pname, params);
}

void GLAPI glIndexPointer( GLenum type, GLsizei stride, const GLvoid *pointer)
{
    (*__gl_dispatch.dispatch.IndexPointer)(type, stride, pointer);
}

void GLAPI glInterleavedArrays( GLenum format, GLsizei stride, const GLvoid *pointer)
{
    (*__gl_dispatch.dispatch.InterleavedArrays)(format, stride, pointer);
}

void GLAPI glNormalPointer( GLenum type, GLsizei stride, const GLvoid *pointer)
{
    (*__gl_dispatch.dispatch.NormalPointer)(type, stride, pointer);
}

void GLAPI glTexCoordPointer( GLint size, GLenum type, GLsizei stride, const GLvoid *pointer)
{
    (*__gl_dispatch.dispatch.TexCoordPointer)(size, type, stride, pointer);
}

void GLAPI glVertexPointer( GLint size, GLenum type, GLsizei stride, const GLvoid *pointer)
{
    (*__gl_dispatch.dispatch.VertexPointer)(size, type, stride, pointer);
}

void GLAPI glPolygonOffset( GLfloat factor, GLfloat units)
{
    (*__gl_dispatch.dispatch.PolygonOffset)(factor, units);
}

void GLAPI glCopyTexImage1D( GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLint border)
{
    (*__gl_dispatch.dispatch.CopyTexImage1D)(target, level, internalformat, x, y, width, border);
}

void GLAPI glCopyTexImage2D( GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border)
{
    (*__gl_dispatch.dispatch.CopyTexImage2D)(target, level, internalformat, x, y, width, height, border);
}

void GLAPI glCopyTexSubImage1D( GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width)
{
    (*__gl_dispatch.dispatch.CopyTexSubImage1D)(target, level, xoffset, x, y, width);
}

void GLAPI glCopyTexSubImage2D( GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height)
{
    (*__gl_dispatch.dispatch.CopyTexSubImage2D)(target, level, xoffset, yoffset, x, y, width, height);
}

void GLAPI glTexSubImage1D( GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid *pixels)
{
    (*__gl_dispatch.dispatch.TexSubImage1D)(target, level, xoffset, width, format, type, pixels);
}

void GLAPI glTexSubImage2D( GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels)
{
    (*__gl_dispatch.dispatch.TexSubImage2D)(target, level, xoffset, yoffset, width, height, format, type, pixels);
}

GLboolean GLAPI glAreTexturesResident( GLsizei n, const GLuint *textures, GLboolean *residences)
{
    return (*__gl_dispatch.dispatch.AreTexturesResident)(n, textures, residences);
}

void GLAPI glBindTexture( GLenum target, GLuint texture)
{
    (*__gl_dispatch.dispatch.BindTexture)(target, texture);
}

void GLAPI glDeleteTextures( GLsizei n, const GLuint *textures)
{
    (*__gl_dispatch.dispatch.DeleteTextures)(n, textures);
}

void GLAPI glGenTextures( GLsizei n, GLuint *textures)
{
    (*__gl_dispatch.dispatch.GenTextures)(n, textures);
}

GLboolean GLAPI glIsTexture( GLuint texture)
{
    return (*__gl_dispatch.dispatch.IsTexture)(texture);
}

void GLAPI glPrioritizeTextures( GLsizei n, const GLuint *textures, const GLclampf *priorities)
{
    (*__gl_dispatch.dispatch.PrioritizeTextures)(n, textures, priorities);
}

void GLAPI glIndexub( GLubyte c)
{
    (*__gl_dispatch.dispatch.Indexub)(c);
}

void GLAPI glIndexubv( const GLubyte *c)
{
    (*__gl_dispatch.dispatch.Indexubv)(c);
}

void GLAPI glPopClientAttrib( void)
{
    (*__gl_dispatch.dispatch.PopClientAttrib)();
}

void GLAPI glPushClientAttrib( GLbitfield mask)
{
    (*__gl_dispatch.dispatch.PushClientAttrib)(mask);
}

void GLAPI glBlendColor( GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
{
    (*__gl_dispatch.dispatch.BlendColor)(red, green, blue, alpha);
}

void GLAPI glBlendEquation( GLenum mode)
{
    (*__gl_dispatch.dispatch.BlendEquation)(mode);
}

void GLAPI glDrawRangeElements( GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const GLvoid *indices)
{
    (*__gl_dispatch.dispatch.DrawRangeElements)(mode, start, end, count, type, indices);
}

void GLAPI glColorTable( GLenum target, GLenum internalformat, GLsizei width, GLenum format, GLenum type, const GLvoid *table)
{
    (*__gl_dispatch.dispatch.ColorTable)(target, internalformat, width, format, type, table);
}

void GLAPI glColorTableParameterfv( GLenum target, GLenum pname, const GLfloat *params)
{
    (*__gl_dispatch.dispatch.ColorTableParameterfv)(target, pname, params);
}

void GLAPI glColorTableParameteriv( GLenum target, GLenum pname, const GLint *params)
{
    (*__gl_dispatch.dispatch.ColorTableParameteriv)(target, pname, params);
}

void GLAPI glCopyColorTable( GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width)
{
    (*__gl_dispatch.dispatch.CopyColorTable)(target, internalformat, x, y, width);
}

void GLAPI glGetColorTable( GLenum target, GLenum format, GLenum type, GLvoid *table)
{
    (*__gl_dispatch.dispatch.GetColorTable)(target, format, type, table);
}

void GLAPI glGetColorTableParameterfv( GLenum target, GLenum pname, GLfloat *params)
{
    (*__gl_dispatch.dispatch.GetColorTableParameterfv)(target, pname, params);
}

void GLAPI glGetColorTableParameteriv( GLenum target, GLenum pname, GLint *params)
{
    (*__gl_dispatch.dispatch.GetColorTableParameteriv)(target, pname, params);
}

void GLAPI glColorSubTable( GLenum target, GLsizei start, GLsizei count, GLenum format, GLenum type, const GLvoid *data)
{
    (*__gl_dispatch.dispatch.ColorSubTable)(target, start, count, format, type, data);
}

void GLAPI glCopyColorSubTable( GLenum target, GLsizei start, GLint x, GLint y, GLsizei width)
{
    (*__gl_dispatch.dispatch.CopyColorSubTable)(target, start, x, y, width);
}

void GLAPI glConvolutionFilter1D( GLenum target, GLenum internalformat, GLsizei width, GLenum format, GLenum type, const GLvoid *image)
{
    (*__gl_dispatch.dispatch.ConvolutionFilter1D)(target, internalformat, width, format, type, image);
}

void GLAPI glConvolutionFilter2D( GLenum target, GLenum internalformat, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *image)
{
    (*__gl_dispatch.dispatch.ConvolutionFilter2D)(target, internalformat, width, height, format, type, image);
}

void GLAPI glConvolutionParameterf( GLenum target, GLenum pname, GLfloat params)
{
    (*__gl_dispatch.dispatch.ConvolutionParameterf)(target, pname, params);
}

void GLAPI glConvolutionParameterfv( GLenum target, GLenum pname, const GLfloat *params)
{
    (*__gl_dispatch.dispatch.ConvolutionParameterfv)(target, pname, params);
}

void GLAPI glConvolutionParameteri( GLenum target, GLenum pname, GLint params)
{
    (*__gl_dispatch.dispatch.ConvolutionParameteri)(target, pname, params);
}

void GLAPI glConvolutionParameteriv( GLenum target, GLenum pname, const GLint *params)
{
    (*__gl_dispatch.dispatch.ConvolutionParameteriv)(target, pname, params);
}

void GLAPI glCopyConvolutionFilter1D( GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width)
{
    (*__gl_dispatch.dispatch.CopyConvolutionFilter1D)(target, internalformat, x, y, width);
}

void GLAPI glCopyConvolutionFilter2D( GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height)
{
    (*__gl_dispatch.dispatch.CopyConvolutionFilter2D)(target, internalformat, x, y, width, height);
}

void GLAPI glGetConvolutionFilter( GLenum target, GLenum format, GLenum type, GLvoid *image)
{
    (*__gl_dispatch.dispatch.GetConvolutionFilter)(target, format, type, image);
}

void GLAPI glGetConvolutionParameterfv( GLenum target, GLenum pname, GLfloat *params)
{
    (*__gl_dispatch.dispatch.GetConvolutionParameterfv)(target, pname, params);
}

void GLAPI glGetConvolutionParameteriv( GLenum target, GLenum pname, GLint *params)
{
    (*__gl_dispatch.dispatch.GetConvolutionParameteriv)(target, pname, params);
}

void GLAPI glGetSeparableFilter( GLenum target, GLenum format, GLenum type, GLvoid *row, GLvoid *column, GLvoid *span)
{
    (*__gl_dispatch.dispatch.GetSeparableFilter)(target, format, type, row, column, span);
}

void GLAPI glSeparableFilter2D( GLenum target, GLenum internalformat, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *row, const GLvoid *column)
{
    (*__gl_dispatch.dispatch.SeparableFilter2D)(target, internalformat, width, height, format, type, row, column);
}

void GLAPI glGetHistogram( GLenum target, GLboolean reset, GLenum format, GLenum type, GLvoid *values)
{
    (*__gl_dispatch.dispatch.GetHistogram)(target, reset, format, type, values);
}

void GLAPI glGetHistogramParameterfv( GLenum target, GLenum pname, GLfloat *params)
{
    (*__gl_dispatch.dispatch.GetHistogramParameterfv)(target, pname, params);
}

void GLAPI glGetHistogramParameteriv( GLenum target, GLenum pname, GLint *params)
{
    (*__gl_dispatch.dispatch.GetHistogramParameteriv)(target, pname, params);
}

void GLAPI glGetMinmax( GLenum target, GLboolean reset, GLenum format, GLenum type, GLvoid *values)
{
    (*__gl_dispatch.dispatch.GetMinmax)(target, reset, format, type, values);
}

void GLAPI glGetMinmaxParameterfv( GLenum target, GLenum pname, GLfloat *params)
{
    (*__gl_dispatch.dispatch.GetMinmaxParameterfv)(target, pname, params);
}

void GLAPI glGetMinmaxParameteriv( GLenum target, GLenum pname, GLint *params)
{
    (*__gl_dispatch.dispatch.GetMinmaxParameteriv)(target, pname, params);
}

void GLAPI glHistogram( GLenum target, GLsizei width, GLenum internalformat, GLboolean sink)
{
    (*__gl_dispatch.dispatch.Histogram)(target, width, internalformat, sink);
}

void GLAPI glMinmax( GLenum target, GLenum internalformat, GLboolean sink)
{
    (*__gl_dispatch.dispatch.Minmax)(target, internalformat, sink);
}

void GLAPI glResetHistogram( GLenum target)
{
    (*__gl_dispatch.dispatch.ResetHistogram)(target);
}

void GLAPI glResetMinmax( GLenum target)
{
    (*__gl_dispatch.dispatch.ResetMinmax)(target);
}

void GLAPI glTexImage3D( GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const GLvoid *pixels)
{
    (*__gl_dispatch.dispatch.TexImage3D)(target, level, internalformat, width, height, depth, border, format, type, pixels);
}

void GLAPI glTexSubImage3D( GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid *pixels)
{
    (*__gl_dispatch.dispatch.TexSubImage3D)(target, level, xoffset, yoffset, zoffset, width, height, depth, format, type, pixels);
}

void GLAPI glCopyTexSubImage3D( GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height)
{
    (*__gl_dispatch.dispatch.CopyTexSubImage3D)(target, level, xoffset, yoffset, zoffset, x, y, width, height);
}

void GLAPI glActiveTextureARB( GLenum texture)
{
    (*__gl_dispatch.dispatch.ActiveTextureARB)(texture);
}

void GLAPI glClientActiveTextureARB( GLenum texture)
{
    (*__gl_dispatch.dispatch.ClientActiveTextureARB)(texture);
}

void GLAPI glMultiTexCoord1dARB( GLenum target, GLdouble s)
{
    (*__gl_dispatch.dispatch.MultiTexCoord1dARB)(target, s);
}

void GLAPI glMultiTexCoord1dvARB( GLenum target, const GLdouble *v)
{
    (*__gl_dispatch.dispatch.MultiTexCoord1dvARB)(target, v);
}

void GLAPI glMultiTexCoord1fARB( GLenum target, GLfloat s)
{
    (*__gl_dispatch.dispatch.MultiTexCoord1fARB)(target, s);
}

void GLAPI glMultiTexCoord1fvARB( GLenum target, const GLfloat *v)
{
    (*__gl_dispatch.dispatch.MultiTexCoord1fvARB)(target, v);
}

void GLAPI glMultiTexCoord1iARB( GLenum target, GLint s)
{
    (*__gl_dispatch.dispatch.MultiTexCoord1iARB)(target, s);
}

void GLAPI glMultiTexCoord1ivARB( GLenum target, const GLint *v)
{
    (*__gl_dispatch.dispatch.MultiTexCoord1ivARB)(target, v);
}

void GLAPI glMultiTexCoord1sARB( GLenum target, GLshort s)
{
    (*__gl_dispatch.dispatch.MultiTexCoord1sARB)(target, s);
}

void GLAPI glMultiTexCoord1svARB( GLenum target, const GLshort *v)
{
    (*__gl_dispatch.dispatch.MultiTexCoord1svARB)(target, v);
}

void GLAPI glMultiTexCoord2dARB( GLenum target, GLdouble s, GLdouble t)
{
    (*__gl_dispatch.dispatch.MultiTexCoord2dARB)(target, s, t);
}

void GLAPI glMultiTexCoord2dvARB( GLenum target, const GLdouble *v)
{
    (*__gl_dispatch.dispatch.MultiTexCoord2dvARB)(target, v);
}

void GLAPI glMultiTexCoord2fARB( GLenum target, GLfloat s, GLfloat t)
{
    (*__gl_dispatch.dispatch.MultiTexCoord2fARB)(target, s, t);
}

void GLAPI glMultiTexCoord2fvARB( GLenum target, const GLfloat *v)
{
    (*__gl_dispatch.dispatch.MultiTexCoord2fvARB)(target, v);
}

void GLAPI glMultiTexCoord2iARB( GLenum target, GLint s, GLint t)
{
    (*__gl_dispatch.dispatch.MultiTexCoord2iARB)(target, s, t);
}

void GLAPI glMultiTexCoord2ivARB( GLenum target, const GLint *v)
{
    (*__gl_dispatch.dispatch.MultiTexCoord2ivARB)(target, v);
}

void GLAPI glMultiTexCoord2sARB( GLenum target, GLshort s, GLshort t)
{
    (*__gl_dispatch.dispatch.MultiTexCoord2sARB)(target, s, t);
}

void GLAPI glMultiTexCoord2svARB( GLenum target, const GLshort *v)
{
    (*__gl_dispatch.dispatch.MultiTexCoord2svARB)(target, v);
}

void GLAPI glMultiTexCoord3dARB( GLenum target, GLdouble s, GLdouble t, GLdouble r)
{
    (*__gl_dispatch.dispatch.MultiTexCoord3dARB)(target, s, t, r);
}

void GLAPI glMultiTexCoord3dvARB( GLenum target, const GLdouble *v)
{
    (*__gl_dispatch.dispatch.MultiTexCoord3dvARB)(target, v);
}

void GLAPI glMultiTexCoord3fARB( GLenum target, GLfloat s, GLfloat t, GLfloat r)
{
    (*__gl_dispatch.dispatch.MultiTexCoord3fARB)(target, s, t, r);
}

void GLAPI glMultiTexCoord3fvARB( GLenum target, const GLfloat *v)
{
    (*__gl_dispatch.dispatch.MultiTexCoord3fvARB)(target, v);
}

void GLAPI glMultiTexCoord3iARB( GLenum target, GLint s, GLint t, GLint r)
{
    (*__gl_dispatch.dispatch.MultiTexCoord3iARB)(target, s, t, r);
}

void GLAPI glMultiTexCoord3ivARB( GLenum target, const GLint *v)
{
    (*__gl_dispatch.dispatch.MultiTexCoord3ivARB)(target, v);
}

void GLAPI glMultiTexCoord3sARB( GLenum target, GLshort s, GLshort t, GLshort r)
{
    (*__gl_dispatch.dispatch.MultiTexCoord3sARB)(target, s, t, r);
}

void GLAPI glMultiTexCoord3svARB( GLenum target, const GLshort *v)
{
    (*__gl_dispatch.dispatch.MultiTexCoord3svARB)(target, v);
}

void GLAPI glMultiTexCoord4dARB( GLenum target, GLdouble s, GLdouble t, GLdouble r, GLdouble q)
{
    (*__gl_dispatch.dispatch.MultiTexCoord4dARB)(target, s, t, r, q);
}

void GLAPI glMultiTexCoord4dvARB( GLenum target, const GLdouble *v)
{
    (*__gl_dispatch.dispatch.MultiTexCoord4dvARB)(target, v);
}

void GLAPI glMultiTexCoord4fARB( GLenum target, GLfloat s, GLfloat t, GLfloat r, GLfloat q)
{
    (*__gl_dispatch.dispatch.MultiTexCoord4fARB)(target, s, t, r, q);
}

void GLAPI glMultiTexCoord4fvARB( GLenum target, const GLfloat *v)
{
    (*__gl_dispatch.dispatch.MultiTexCoord4fvARB)(target, v);
}

void GLAPI glMultiTexCoord4iARB( GLenum target, GLint s, GLint t, GLint r, GLint q)
{
    (*__gl_dispatch.dispatch.MultiTexCoord4iARB)(target, s, t, r, q);
}

void GLAPI glMultiTexCoord4ivARB( GLenum target, const GLint *v)
{
    (*__gl_dispatch.dispatch.MultiTexCoord4ivARB)(target, v);
}

void GLAPI glMultiTexCoord4sARB( GLenum target, GLshort s, GLshort t, GLshort r, GLshort q)
{
    (*__gl_dispatch.dispatch.MultiTexCoord4sARB)(target, s, t, r, q);
}

void GLAPI glMultiTexCoord4svARB( GLenum target, const GLshort *v)
{
    (*__gl_dispatch.dispatch.MultiTexCoord4svARB)(target, v);
}

void GLAPI glLockArraysEXT( GLint first, GLsizei count)
{
    (*__gl_dispatch.dispatch.LockArraysEXT)(first, count);
}

void GLAPI glUnlockArraysEXT( void)
{
    (*__gl_dispatch.dispatch.UnlockArraysEXT)();
}

void GLAPI glArrayElementEXT( GLint i)
{
    (*__gl_dispatch.dispatch.ArrayElementEXT)(i);
}

void GLAPI glColorPointerEXT( GLint size, GLenum type, GLsizei stride, GLsizei count, const GLvoid *pointer)
{
    (*__gl_dispatch.dispatch.ColorPointerEXT)(size, type, stride, count, pointer);
}

void GLAPI glEdgeFlagPointerEXT( GLsizei stride, GLsizei count, const GLboolean *pointer)
{
    (*__gl_dispatch.dispatch.EdgeFlagPointerEXT)(stride, count, pointer);
}

void GLAPI glGetPointervEXT( GLenum pname, GLvoid* *params)
{
    (*__gl_dispatch.dispatch.GetPointervEXT)(pname, params);
}

void GLAPI glIndexPointerEXT( GLenum type, GLsizei stride, GLsizei count, const GLvoid *pointer)
{
    (*__gl_dispatch.dispatch.IndexPointerEXT)(type, stride, count, pointer);
}

void GLAPI glNormalPointerEXT( GLenum type, GLsizei stride, GLsizei count, const GLvoid *pointer)
{
    (*__gl_dispatch.dispatch.NormalPointerEXT)(type, stride, count, pointer);
}

void GLAPI glTexCoordPointerEXT( GLint size, GLenum type, GLsizei stride, GLsizei count, const GLvoid *pointer)
{
    (*__gl_dispatch.dispatch.TexCoordPointerEXT)(size, type, stride, count, pointer);
}

void GLAPI glVertexPointerEXT( GLint size, GLenum type, GLsizei stride, GLsizei count, const GLvoid *pointer)
{
    (*__gl_dispatch.dispatch.VertexPointerEXT)(size, type, stride, count, pointer);
}

void GLAPI glDrawArraysEXT( GLenum mode, GLint first, GLsizei count)
{
    (*__gl_dispatch.dispatch.DrawArraysEXT)(mode, first, count);
}

GLboolean GLAPI glAreTexturesResidentEXT( GLsizei n, const GLuint *textures, GLboolean *residences)
{
    return (*__gl_dispatch.dispatch.AreTexturesResidentEXT)(n, textures, residences);
}

void GLAPI glDeleteTexturesEXT( GLsizei n, const GLuint *textures)
{
    (*__gl_dispatch.dispatch.DeleteTexturesEXT)(n, textures);
}

void GLAPI glGenTexturesEXT( GLsizei n, GLuint *textures)
{
    (*__gl_dispatch.dispatch.GenTexturesEXT)(n, textures);
}

GLboolean GLAPI glIsTextureEXT( GLuint texture)
{
    return (*__gl_dispatch.dispatch.IsTextureEXT)(texture);
}

