
/* DO NOT EDIT - THIS FILE IS AUTOMATICALLY GENERATED */

/*
** License Applicability. Except to the extent portions of this file are
** made subject to an alternative license as permitted in the SGI Free
** Software License B, Version 1.1 (the "License"), the contents of this
** file are subject only to the provisions of the License. You may not use
** this file except in compliance with the License. You may obtain a copy
** of the License at Silicon Graphics, Inc., attn: Legal Services, 1600
** Amphitheatre Parkway, Mountain View, CA 94043-1351, or at:
**
** http://oss.sgi.com/projects/FreeB
**
** Note that, as provided in the License, the Software is distributed on an
** "AS IS" basis, with ALL EXPRESS AND IMPLIED WARRANTIES AND CONDITIONS
** DISCLAIMED, INCLUDING, WITHOUT LIMITATION, ANY IMPLIED WARRANTIES AND
** CONDITIONS OF MERCHANTABILITY, SATISFACTORY QUALITY, FITNESS FOR A
** PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
**
** Original Code. The Original Code is: OpenGL Sample Implementation,
** Version 1.2.1, released January 26, 2000, developed by Silicon Graphics,
** License Applicability. Except to the extent portions of this file are
** made subject to an alternative license as permitted in the SGI Free
** Software License B, Version 1.1 (the "License"), the contents of this
** file are subject only to the provisions of the License. You may not use
** this file except in compliance with the License. You may obtain a copy
** of the License at Silicon Graphics, Inc., attn: Legal Services, 1600
** Amphitheatre Parkway, Mountain View, CA 94043-1351, or at:
** 
** http://oss.sgi.com/projects/FreeB
** 
** Note that, as provided in the License, the Software is distributed on an
** "AS IS" basis, with ALL EXPRESS AND IMPLIED WARRANTIES AND CONDITIONS
** DISCLAIMED, INCLUDING, WITHOUT LIMITATION, ANY IMPLIED WARRANTIES AND
** CONDITIONS OF MERCHANTABILITY, SATISFACTORY QUALITY, FITNESS FOR A
** PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
** 
** Original Code. The Original Code is: OpenGL Sample Implementation,
** Version 1.2.1, released January 26, 2000, developed by Silicon Graphics,
** Inc. The Original Code is Copyright (c) 1991-2000 Silicon Graphics, Inc.
** Copyright in any portions created by third parties is as indicated
** elsewhere herein. All Rights Reserved.
** 
** Additional Notice Provisions: The application programming interfaces
** established by SGI in conjunction with the Original Code are The
** OpenGL(R) Graphics System: A Specification (Version 1.2.1), released
** April 1, 1999; The OpenGL(R) Graphics System Utility Library (Version
** 1.3), released November 4, 1998; and OpenGL(R) Graphics with the X
** Window System(R) (Version 1.3), released October 19, 1998. This software
** was created using the OpenGL(R) version 1.2.1 Sample Implementation
** published by SGI, but has not been independently verified as being
** compliant with the OpenGL(R) version 1.2.1 Specification.
**
*/

/* This file generated by dlist.ls -- DO NOT EDIT! */
#include "context.h"
#include "global.h"
#include "dlist.h"
#include "dlistopt.h"
#include "g_lcomp.h"
#include "g_listop.h"
#include "g_imports.h"
#include "g_lcefncs.h"
#include "g_lcomp.h"

const GLubyte *__glle_ListBase(const GLubyte *PC)
{
    const struct __gllc_ListBase_Rec *data;

    data = (const struct __gllc_ListBase_Rec *) PC;
    (*__gl_dispatch.dispatch.ListBase)(data->base);
    return PC + sizeof(struct __gllc_ListBase_Rec);
}

const GLubyte *__glle_Color3bv(const GLubyte *PC)
{
    const struct __gllc_Color3bv_Rec *data;

    data = (const struct __gllc_Color3bv_Rec *) PC;
    (*__gl_dispatch.dispatch.Color3bv)(data->v);
    return PC + sizeof(struct __gllc_Color3bv_Rec);
}

const GLubyte *__glle_Color3dv(const GLubyte *PC)
{
    const struct __gllc_Color3dv_Rec *data;

    data = (const struct __gllc_Color3dv_Rec *) PC;
    (*__gl_dispatch.dispatch.Color3dv)(data->v);
    return PC + sizeof(struct __gllc_Color3dv_Rec);
}

const GLubyte *__glle_Color3fv(const GLubyte *PC)
{
    const struct __gllc_Color3fv_Rec *data;

    data = (const struct __gllc_Color3fv_Rec *) PC;
    (*__gl_dispatch.dispatch.Color3fv)(data->v);
    return PC + sizeof(struct __gllc_Color3fv_Rec);
}

const GLubyte *__glle_Color3iv(const GLubyte *PC)
{
    const struct __gllc_Color3iv_Rec *data;

    data = (const struct __gllc_Color3iv_Rec *) PC;
    (*__gl_dispatch.dispatch.Color3iv)(data->v);
    return PC + sizeof(struct __gllc_Color3iv_Rec);
}

const GLubyte *__glle_Color3sv(const GLubyte *PC)
{
    const struct __gllc_Color3sv_Rec *data;

    data = (const struct __gllc_Color3sv_Rec *) PC;
    (*__gl_dispatch.dispatch.Color3sv)(data->v);
    return PC + sizeof(struct __gllc_Color3sv_Rec);
}

const GLubyte *__glle_Color3ubv(const GLubyte *PC)
{
    const struct __gllc_Color3ubv_Rec *data;

    data = (const struct __gllc_Color3ubv_Rec *) PC;
    (*__gl_dispatch.dispatch.Color3ubv)(data->v);
    return PC + sizeof(struct __gllc_Color3ubv_Rec);
}

const GLubyte *__glle_Color3uiv(const GLubyte *PC)
{
    const struct __gllc_Color3uiv_Rec *data;

    data = (const struct __gllc_Color3uiv_Rec *) PC;
    (*__gl_dispatch.dispatch.Color3uiv)(data->v);
    return PC + sizeof(struct __gllc_Color3uiv_Rec);
}

const GLubyte *__glle_Color3usv(const GLubyte *PC)
{
    const struct __gllc_Color3usv_Rec *data;

    data = (const struct __gllc_Color3usv_Rec *) PC;
    (*__gl_dispatch.dispatch.Color3usv)(data->v);
    return PC + sizeof(struct __gllc_Color3usv_Rec);
}

const GLubyte *__glle_Color4bv(const GLubyte *PC)
{
    const struct __gllc_Color4bv_Rec *data;

    data = (const struct __gllc_Color4bv_Rec *) PC;
    (*__gl_dispatch.dispatch.Color4bv)(data->v);
    return PC + sizeof(struct __gllc_Color4bv_Rec);
}

const GLubyte *__glle_Color4dv(const GLubyte *PC)
{
    const struct __gllc_Color4dv_Rec *data;

    data = (const struct __gllc_Color4dv_Rec *) PC;
    (*__gl_dispatch.dispatch.Color4dv)(data->v);
    return PC + sizeof(struct __gllc_Color4dv_Rec);
}

const GLubyte *__glle_Color4fv(const GLubyte *PC)
{
    const struct __gllc_Color4fv_Rec *data;

    data = (const struct __gllc_Color4fv_Rec *) PC;
    (*__gl_dispatch.dispatch.Color4fv)(data->v);
    return PC + sizeof(struct __gllc_Color4fv_Rec);
}

const GLubyte *__glle_Color4iv(const GLubyte *PC)
{
    const struct __gllc_Color4iv_Rec *data;

    data = (const struct __gllc_Color4iv_Rec *) PC;
    (*__gl_dispatch.dispatch.Color4iv)(data->v);
    return PC + sizeof(struct __gllc_Color4iv_Rec);
}

const GLubyte *__glle_Color4sv(const GLubyte *PC)
{
    const struct __gllc_Color4sv_Rec *data;

    data = (const struct __gllc_Color4sv_Rec *) PC;
    (*__gl_dispatch.dispatch.Color4sv)(data->v);
    return PC + sizeof(struct __gllc_Color4sv_Rec);
}

const GLubyte *__glle_Color4ubv(const GLubyte *PC)
{
    const struct __gllc_Color4ubv_Rec *data;

    data = (const struct __gllc_Color4ubv_Rec *) PC;
    (*__gl_dispatch.dispatch.Color4ubv)(data->v);
    return PC + sizeof(struct __gllc_Color4ubv_Rec);
}

const GLubyte *__glle_Color4uiv(const GLubyte *PC)
{
    const struct __gllc_Color4uiv_Rec *data;

    data = (const struct __gllc_Color4uiv_Rec *) PC;
    (*__gl_dispatch.dispatch.Color4uiv)(data->v);
    return PC + sizeof(struct __gllc_Color4uiv_Rec);
}

const GLubyte *__glle_Color4usv(const GLubyte *PC)
{
    const struct __gllc_Color4usv_Rec *data;

    data = (const struct __gllc_Color4usv_Rec *) PC;
    (*__gl_dispatch.dispatch.Color4usv)(data->v);
    return PC + sizeof(struct __gllc_Color4usv_Rec);
}

const GLubyte *__glle_EdgeFlagv(const GLubyte *PC)
{
    const struct __gllc_EdgeFlagv_Rec *data;

    data = (const struct __gllc_EdgeFlagv_Rec *) PC;
    (*__gl_dispatch.dispatch.EdgeFlagv)(data->flag);
    return PC + sizeof(struct __gllc_EdgeFlagv_Rec);
}

const GLubyte *__glle_End(const GLubyte *PC)
{

    (*__gl_dispatch.dispatch.End)();
    return PC;
}

const GLubyte *__glle_Indexdv(const GLubyte *PC)
{
    const struct __gllc_Indexdv_Rec *data;

    data = (const struct __gllc_Indexdv_Rec *) PC;
    (*__gl_dispatch.dispatch.Indexdv)(data->c);
    return PC + sizeof(struct __gllc_Indexdv_Rec);
}

const GLubyte *__glle_Indexfv(const GLubyte *PC)
{
    const struct __gllc_Indexfv_Rec *data;

    data = (const struct __gllc_Indexfv_Rec *) PC;
    (*__gl_dispatch.dispatch.Indexfv)(data->c);
    return PC + sizeof(struct __gllc_Indexfv_Rec);
}

const GLubyte *__glle_Indexiv(const GLubyte *PC)
{
    const struct __gllc_Indexiv_Rec *data;

    data = (const struct __gllc_Indexiv_Rec *) PC;
    (*__gl_dispatch.dispatch.Indexiv)(data->c);
    return PC + sizeof(struct __gllc_Indexiv_Rec);
}

const GLubyte *__glle_Indexsv(const GLubyte *PC)
{
    const struct __gllc_Indexsv_Rec *data;

    data = (const struct __gllc_Indexsv_Rec *) PC;
    (*__gl_dispatch.dispatch.Indexsv)(data->c);
    return PC + sizeof(struct __gllc_Indexsv_Rec);
}

const GLubyte *__glle_Normal3bv(const GLubyte *PC)
{
    const struct __gllc_Normal3bv_Rec *data;

    data = (const struct __gllc_Normal3bv_Rec *) PC;
    (*__gl_dispatch.dispatch.Normal3bv)(data->v);
    return PC + sizeof(struct __gllc_Normal3bv_Rec);
}

const GLubyte *__glle_Normal3dv(const GLubyte *PC)
{
    const struct __gllc_Normal3dv_Rec *data;

    data = (const struct __gllc_Normal3dv_Rec *) PC;
    (*__gl_dispatch.dispatch.Normal3dv)(data->v);
    return PC + sizeof(struct __gllc_Normal3dv_Rec);
}

const GLubyte *__glle_Normal3fv(const GLubyte *PC)
{
    const struct __gllc_Normal3fv_Rec *data;

    data = (const struct __gllc_Normal3fv_Rec *) PC;
    (*__gl_dispatch.dispatch.Normal3fv)(data->v);
    return PC + sizeof(struct __gllc_Normal3fv_Rec);
}

const GLubyte *__glle_Normal3iv(const GLubyte *PC)
{
    const struct __gllc_Normal3iv_Rec *data;

    data = (const struct __gllc_Normal3iv_Rec *) PC;
    (*__gl_dispatch.dispatch.Normal3iv)(data->v);
    return PC + sizeof(struct __gllc_Normal3iv_Rec);
}

const GLubyte *__glle_Normal3sv(const GLubyte *PC)
{
    const struct __gllc_Normal3sv_Rec *data;

    data = (const struct __gllc_Normal3sv_Rec *) PC;
    (*__gl_dispatch.dispatch.Normal3sv)(data->v);
    return PC + sizeof(struct __gllc_Normal3sv_Rec);
}

const GLubyte *__glle_RasterPos2dv(const GLubyte *PC)
{
    const struct __gllc_RasterPos2dv_Rec *data;

    data = (const struct __gllc_RasterPos2dv_Rec *) PC;
    (*__gl_dispatch.dispatch.RasterPos2dv)(data->v);
    return PC + sizeof(struct __gllc_RasterPos2dv_Rec);
}

const GLubyte *__glle_RasterPos2fv(const GLubyte *PC)
{
    const struct __gllc_RasterPos2fv_Rec *data;

    data = (const struct __gllc_RasterPos2fv_Rec *) PC;
    (*__gl_dispatch.dispatch.RasterPos2fv)(data->v);
    return PC + sizeof(struct __gllc_RasterPos2fv_Rec);
}

const GLubyte *__glle_RasterPos2iv(const GLubyte *PC)
{
    const struct __gllc_RasterPos2iv_Rec *data;

    data = (const struct __gllc_RasterPos2iv_Rec *) PC;
    (*__gl_dispatch.dispatch.RasterPos2iv)(data->v);
    return PC + sizeof(struct __gllc_RasterPos2iv_Rec);
}

const GLubyte *__glle_RasterPos2sv(const GLubyte *PC)
{
    const struct __gllc_RasterPos2sv_Rec *data;

    data = (const struct __gllc_RasterPos2sv_Rec *) PC;
    (*__gl_dispatch.dispatch.RasterPos2sv)(data->v);
    return PC + sizeof(struct __gllc_RasterPos2sv_Rec);
}

const GLubyte *__glle_RasterPos3dv(const GLubyte *PC)
{
    const struct __gllc_RasterPos3dv_Rec *data;

    data = (const struct __gllc_RasterPos3dv_Rec *) PC;
    (*__gl_dispatch.dispatch.RasterPos3dv)(data->v);
    return PC + sizeof(struct __gllc_RasterPos3dv_Rec);
}

const GLubyte *__glle_RasterPos3fv(const GLubyte *PC)
{
    const struct __gllc_RasterPos3fv_Rec *data;

    data = (const struct __gllc_RasterPos3fv_Rec *) PC;
    (*__gl_dispatch.dispatch.RasterPos3fv)(data->v);
    return PC + sizeof(struct __gllc_RasterPos3fv_Rec);
}

const GLubyte *__glle_RasterPos3iv(const GLubyte *PC)
{
    const struct __gllc_RasterPos3iv_Rec *data;

    data = (const struct __gllc_RasterPos3iv_Rec *) PC;
    (*__gl_dispatch.dispatch.RasterPos3iv)(data->v);
    return PC + sizeof(struct __gllc_RasterPos3iv_Rec);
}

const GLubyte *__glle_RasterPos3sv(const GLubyte *PC)
{
    const struct __gllc_RasterPos3sv_Rec *data;

    data = (const struct __gllc_RasterPos3sv_Rec *) PC;
    (*__gl_dispatch.dispatch.RasterPos3sv)(data->v);
    return PC + sizeof(struct __gllc_RasterPos3sv_Rec);
}

const GLubyte *__glle_RasterPos4dv(const GLubyte *PC)
{
    const struct __gllc_RasterPos4dv_Rec *data;

    data = (const struct __gllc_RasterPos4dv_Rec *) PC;
    (*__gl_dispatch.dispatch.RasterPos4dv)(data->v);
    return PC + sizeof(struct __gllc_RasterPos4dv_Rec);
}

const GLubyte *__glle_RasterPos4fv(const GLubyte *PC)
{
    const struct __gllc_RasterPos4fv_Rec *data;

    data = (const struct __gllc_RasterPos4fv_Rec *) PC;
    (*__gl_dispatch.dispatch.RasterPos4fv)(data->v);
    return PC + sizeof(struct __gllc_RasterPos4fv_Rec);
}

const GLubyte *__glle_RasterPos4iv(const GLubyte *PC)
{
    const struct __gllc_RasterPos4iv_Rec *data;

    data = (const struct __gllc_RasterPos4iv_Rec *) PC;
    (*__gl_dispatch.dispatch.RasterPos4iv)(data->v);
    return PC + sizeof(struct __gllc_RasterPos4iv_Rec);
}

const GLubyte *__glle_RasterPos4sv(const GLubyte *PC)
{
    const struct __gllc_RasterPos4sv_Rec *data;

    data = (const struct __gllc_RasterPos4sv_Rec *) PC;
    (*__gl_dispatch.dispatch.RasterPos4sv)(data->v);
    return PC + sizeof(struct __gllc_RasterPos4sv_Rec);
}

const GLubyte *__glle_Rectdv(const GLubyte *PC)
{
    const struct __gllc_Rectdv_Rec *data;

    data = (const struct __gllc_Rectdv_Rec *) PC;
    (*__gl_dispatch.dispatch.Rectdv)(data->v1, data->v2);
    return PC + sizeof(struct __gllc_Rectdv_Rec);
}

const GLubyte *__glle_Rectfv(const GLubyte *PC)
{
    const struct __gllc_Rectfv_Rec *data;

    data = (const struct __gllc_Rectfv_Rec *) PC;
    (*__gl_dispatch.dispatch.Rectfv)(data->v1, data->v2);
    return PC + sizeof(struct __gllc_Rectfv_Rec);
}

const GLubyte *__glle_Rectiv(const GLubyte *PC)
{
    const struct __gllc_Rectiv_Rec *data;

    data = (const struct __gllc_Rectiv_Rec *) PC;
    (*__gl_dispatch.dispatch.Rectiv)(data->v1, data->v2);
    return PC + sizeof(struct __gllc_Rectiv_Rec);
}

const GLubyte *__glle_Rectsv(const GLubyte *PC)
{
    const struct __gllc_Rectsv_Rec *data;

    data = (const struct __gllc_Rectsv_Rec *) PC;
    (*__gl_dispatch.dispatch.Rectsv)(data->v1, data->v2);
    return PC + sizeof(struct __gllc_Rectsv_Rec);
}

const GLubyte *__glle_TexCoord1dv(const GLubyte *PC)
{
    const struct __gllc_TexCoord1dv_Rec *data;

    data = (const struct __gllc_TexCoord1dv_Rec *) PC;
    (*__gl_dispatch.dispatch.TexCoord1dv)(data->v);
    return PC + sizeof(struct __gllc_TexCoord1dv_Rec);
}

const GLubyte *__glle_TexCoord1fv(const GLubyte *PC)
{
    const struct __gllc_TexCoord1fv_Rec *data;

    data = (const struct __gllc_TexCoord1fv_Rec *) PC;
    (*__gl_dispatch.dispatch.TexCoord1fv)(data->v);
    return PC + sizeof(struct __gllc_TexCoord1fv_Rec);
}

const GLubyte *__glle_TexCoord1iv(const GLubyte *PC)
{
    const struct __gllc_TexCoord1iv_Rec *data;

    data = (const struct __gllc_TexCoord1iv_Rec *) PC;
    (*__gl_dispatch.dispatch.TexCoord1iv)(data->v);
    return PC + sizeof(struct __gllc_TexCoord1iv_Rec);
}

const GLubyte *__glle_TexCoord1sv(const GLubyte *PC)
{
    const struct __gllc_TexCoord1sv_Rec *data;

    data = (const struct __gllc_TexCoord1sv_Rec *) PC;
    (*__gl_dispatch.dispatch.TexCoord1sv)(data->v);
    return PC + sizeof(struct __gllc_TexCoord1sv_Rec);
}

const GLubyte *__glle_TexCoord2dv(const GLubyte *PC)
{
    const struct __gllc_TexCoord2dv_Rec *data;

    data = (const struct __gllc_TexCoord2dv_Rec *) PC;
    (*__gl_dispatch.dispatch.TexCoord2dv)(data->v);
    return PC + sizeof(struct __gllc_TexCoord2dv_Rec);
}

const GLubyte *__glle_TexCoord2fv(const GLubyte *PC)
{
    const struct __gllc_TexCoord2fv_Rec *data;

    data = (const struct __gllc_TexCoord2fv_Rec *) PC;
    (*__gl_dispatch.dispatch.TexCoord2fv)(data->v);
    return PC + sizeof(struct __gllc_TexCoord2fv_Rec);
}

const GLubyte *__glle_TexCoord2iv(const GLubyte *PC)
{
    const struct __gllc_TexCoord2iv_Rec *data;

    data = (const struct __gllc_TexCoord2iv_Rec *) PC;
    (*__gl_dispatch.dispatch.TexCoord2iv)(data->v);
    return PC + sizeof(struct __gllc_TexCoord2iv_Rec);
}

const GLubyte *__glle_TexCoord2sv(const GLubyte *PC)
{
    const struct __gllc_TexCoord2sv_Rec *data;

    data = (const struct __gllc_TexCoord2sv_Rec *) PC;
    (*__gl_dispatch.dispatch.TexCoord2sv)(data->v);
    return PC + sizeof(struct __gllc_TexCoord2sv_Rec);
}

const GLubyte *__glle_TexCoord3dv(const GLubyte *PC)
{
    const struct __gllc_TexCoord3dv_Rec *data;

    data = (const struct __gllc_TexCoord3dv_Rec *) PC;
    (*__gl_dispatch.dispatch.TexCoord3dv)(data->v);
    return PC + sizeof(struct __gllc_TexCoord3dv_Rec);
}

const GLubyte *__glle_TexCoord3fv(const GLubyte *PC)
{
    const struct __gllc_TexCoord3fv_Rec *data;

    data = (const struct __gllc_TexCoord3fv_Rec *) PC;
    (*__gl_dispatch.dispatch.TexCoord3fv)(data->v);
    return PC + sizeof(struct __gllc_TexCoord3fv_Rec);
}

const GLubyte *__glle_TexCoord3iv(const GLubyte *PC)
{
    const struct __gllc_TexCoord3iv_Rec *data;

    data = (const struct __gllc_TexCoord3iv_Rec *) PC;
    (*__gl_dispatch.dispatch.TexCoord3iv)(data->v);
    return PC + sizeof(struct __gllc_TexCoord3iv_Rec);
}

const GLubyte *__glle_TexCoord3sv(const GLubyte *PC)
{
    const struct __gllc_TexCoord3sv_Rec *data;

    data = (const struct __gllc_TexCoord3sv_Rec *) PC;
    (*__gl_dispatch.dispatch.TexCoord3sv)(data->v);
    return PC + sizeof(struct __gllc_TexCoord3sv_Rec);
}

const GLubyte *__glle_TexCoord4dv(const GLubyte *PC)
{
    const struct __gllc_TexCoord4dv_Rec *data;

    data = (const struct __gllc_TexCoord4dv_Rec *) PC;
    (*__gl_dispatch.dispatch.TexCoord4dv)(data->v);
    return PC + sizeof(struct __gllc_TexCoord4dv_Rec);
}

const GLubyte *__glle_TexCoord4fv(const GLubyte *PC)
{
    const struct __gllc_TexCoord4fv_Rec *data;

    data = (const struct __gllc_TexCoord4fv_Rec *) PC;
    (*__gl_dispatch.dispatch.TexCoord4fv)(data->v);
    return PC + sizeof(struct __gllc_TexCoord4fv_Rec);
}

const GLubyte *__glle_TexCoord4iv(const GLubyte *PC)
{
    const struct __gllc_TexCoord4iv_Rec *data;

    data = (const struct __gllc_TexCoord4iv_Rec *) PC;
    (*__gl_dispatch.dispatch.TexCoord4iv)(data->v);
    return PC + sizeof(struct __gllc_TexCoord4iv_Rec);
}

const GLubyte *__glle_TexCoord4sv(const GLubyte *PC)
{
    const struct __gllc_TexCoord4sv_Rec *data;

    data = (const struct __gllc_TexCoord4sv_Rec *) PC;
    (*__gl_dispatch.dispatch.TexCoord4sv)(data->v);
    return PC + sizeof(struct __gllc_TexCoord4sv_Rec);
}

const GLubyte *__glle_Vertex2dv(const GLubyte *PC)
{
    const struct __gllc_Vertex2dv_Rec *data;

    data = (const struct __gllc_Vertex2dv_Rec *) PC;
    (*__gl_dispatch.dispatch.Vertex2dv)(data->v);
    return PC + sizeof(struct __gllc_Vertex2dv_Rec);
}

const GLubyte *__glle_Vertex2fv(const GLubyte *PC)
{
    const struct __gllc_Vertex2fv_Rec *data;

    data = (const struct __gllc_Vertex2fv_Rec *) PC;
    (*__gl_dispatch.dispatch.Vertex2fv)(data->v);
    return PC + sizeof(struct __gllc_Vertex2fv_Rec);
}

const GLubyte *__glle_Vertex2iv(const GLubyte *PC)
{
    const struct __gllc_Vertex2iv_Rec *data;

    data = (const struct __gllc_Vertex2iv_Rec *) PC;
    (*__gl_dispatch.dispatch.Vertex2iv)(data->v);
    return PC + sizeof(struct __gllc_Vertex2iv_Rec);
}

const GLubyte *__glle_Vertex2sv(const GLubyte *PC)
{
    const struct __gllc_Vertex2sv_Rec *data;

    data = (const struct __gllc_Vertex2sv_Rec *) PC;
    (*__gl_dispatch.dispatch.Vertex2sv)(data->v);
    return PC + sizeof(struct __gllc_Vertex2sv_Rec);
}

const GLubyte *__glle_Vertex3dv(const GLubyte *PC)
{
    const struct __gllc_Vertex3dv_Rec *data;

    data = (const struct __gllc_Vertex3dv_Rec *) PC;
    (*__gl_dispatch.dispatch.Vertex3dv)(data->v);
    return PC + sizeof(struct __gllc_Vertex3dv_Rec);
}

const GLubyte *__glle_Vertex3fv(const GLubyte *PC)
{
    const struct __gllc_Vertex3fv_Rec *data;

    data = (const struct __gllc_Vertex3fv_Rec *) PC;
    (*__gl_dispatch.dispatch.Vertex3fv)(data->v);
    return PC + sizeof(struct __gllc_Vertex3fv_Rec);
}

const GLubyte *__glle_Vertex3iv(const GLubyte *PC)
{
    const struct __gllc_Vertex3iv_Rec *data;

    data = (const struct __gllc_Vertex3iv_Rec *) PC;
    (*__gl_dispatch.dispatch.Vertex3iv)(data->v);
    return PC + sizeof(struct __gllc_Vertex3iv_Rec);
}

const GLubyte *__glle_Vertex3sv(const GLubyte *PC)
{
    const struct __gllc_Vertex3sv_Rec *data;

    data = (const struct __gllc_Vertex3sv_Rec *) PC;
    (*__gl_dispatch.dispatch.Vertex3sv)(data->v);
    return PC + sizeof(struct __gllc_Vertex3sv_Rec);
}

const GLubyte *__glle_Vertex4dv(const GLubyte *PC)
{
    const struct __gllc_Vertex4dv_Rec *data;

    data = (const struct __gllc_Vertex4dv_Rec *) PC;
    (*__gl_dispatch.dispatch.Vertex4dv)(data->v);
    return PC + sizeof(struct __gllc_Vertex4dv_Rec);
}

const GLubyte *__glle_Vertex4fv(const GLubyte *PC)
{
    const struct __gllc_Vertex4fv_Rec *data;

    data = (const struct __gllc_Vertex4fv_Rec *) PC;
    (*__gl_dispatch.dispatch.Vertex4fv)(data->v);
    return PC + sizeof(struct __gllc_Vertex4fv_Rec);
}

const GLubyte *__glle_Vertex4iv(const GLubyte *PC)
{
    const struct __gllc_Vertex4iv_Rec *data;

    data = (const struct __gllc_Vertex4iv_Rec *) PC;
    (*__gl_dispatch.dispatch.Vertex4iv)(data->v);
    return PC + sizeof(struct __gllc_Vertex4iv_Rec);
}

const GLubyte *__glle_Vertex4sv(const GLubyte *PC)
{
    const struct __gllc_Vertex4sv_Rec *data;

    data = (const struct __gllc_Vertex4sv_Rec *) PC;
    (*__gl_dispatch.dispatch.Vertex4sv)(data->v);
    return PC + sizeof(struct __gllc_Vertex4sv_Rec);
}

const GLubyte *__glle_ClipPlane(const GLubyte *PC)
{
    const struct __gllc_ClipPlane_Rec *data;

    data = (const struct __gllc_ClipPlane_Rec *) PC;
    (*__gl_dispatch.dispatch.ClipPlane)(data->plane, data->equation);
    return PC + sizeof(struct __gllc_ClipPlane_Rec);
}

const GLubyte *__glle_ColorMaterial(const GLubyte *PC)
{
    const struct __gllc_ColorMaterial_Rec *data;

    data = (const struct __gllc_ColorMaterial_Rec *) PC;
    (*__gl_dispatch.dispatch.ColorMaterial)(data->face, data->mode);
    return PC + sizeof(struct __gllc_ColorMaterial_Rec);
}

const GLubyte *__glle_CullFace(const GLubyte *PC)
{
    const struct __gllc_CullFace_Rec *data;

    data = (const struct __gllc_CullFace_Rec *) PC;
    (*__gl_dispatch.dispatch.CullFace)(data->mode);
    return PC + sizeof(struct __gllc_CullFace_Rec);
}

const GLubyte *__glle_Fogf(const GLubyte *PC)
{
    const struct __gllc_Fogf_Rec *data;

    data = (const struct __gllc_Fogf_Rec *) PC;
    (*__gl_dispatch.dispatch.Fogf)(data->pname, data->param);
    return PC + sizeof(struct __gllc_Fogf_Rec);
}

const GLubyte *__glle_Fogfv(const GLubyte *PC)
{
    GLuint size;
    GLuint arraySize;
    const struct __gllc_Fogfv_Rec *data;

    data = (const struct __gllc_Fogfv_Rec *) PC;
    (*__gl_dispatch.dispatch.Fogfv)(data->pname, 
	    (const GLfloat *) (PC + sizeof(struct __gllc_Fogfv_Rec)));
    arraySize = __GL64PAD(__glFogfv_size(data->pname) * 4);
    size = (GLuint)sizeof(struct __gllc_Fogfv_Rec) + arraySize;
    return PC + size;
}

const GLubyte *__glle_Fogi(const GLubyte *PC)
{
    const struct __gllc_Fogi_Rec *data;

    data = (const struct __gllc_Fogi_Rec *) PC;
    (*__gl_dispatch.dispatch.Fogi)(data->pname, data->param);
    return PC + sizeof(struct __gllc_Fogi_Rec);
}

const GLubyte *__glle_Fogiv(const GLubyte *PC)
{
    GLuint size;
    GLuint arraySize;
    const struct __gllc_Fogiv_Rec *data;

    data = (const struct __gllc_Fogiv_Rec *) PC;
    (*__gl_dispatch.dispatch.Fogiv)(data->pname, 
	    (const GLint *) (PC + sizeof(struct __gllc_Fogiv_Rec)));
    arraySize = __GL64PAD(__glFogiv_size(data->pname) * 4);
    size = (GLuint)sizeof(struct __gllc_Fogiv_Rec) + arraySize;
    return PC + size;
}

const GLubyte *__glle_FrontFace(const GLubyte *PC)
{
    const struct __gllc_FrontFace_Rec *data;

    data = (const struct __gllc_FrontFace_Rec *) PC;
    (*__gl_dispatch.dispatch.FrontFace)(data->mode);
    return PC + sizeof(struct __gllc_FrontFace_Rec);
}

const GLubyte *__glle_Hint(const GLubyte *PC)
{
    const struct __gllc_Hint_Rec *data;

    data = (const struct __gllc_Hint_Rec *) PC;
    (*__gl_dispatch.dispatch.Hint)(data->target, data->mode);
    return PC + sizeof(struct __gllc_Hint_Rec);
}

const GLubyte *__glle_Lightfv(const GLubyte *PC)
{
    GLuint size;
    GLuint arraySize;
    const struct __gllc_Lightfv_Rec *data;

    data = (const struct __gllc_Lightfv_Rec *) PC;
    (*__gl_dispatch.dispatch.Lightfv)(data->light, data->pname, 
	    (const GLfloat *) (PC + sizeof(struct __gllc_Lightfv_Rec)));
    arraySize = __GL64PAD(__glLightfv_size(data->pname) * 4);
    size = (GLuint)sizeof(struct __gllc_Lightfv_Rec) + arraySize;
    return PC + size;
}

const GLubyte *__glle_Lightiv(const GLubyte *PC)
{
    GLuint size;
    GLuint arraySize;
    const struct __gllc_Lightiv_Rec *data;

    data = (const struct __gllc_Lightiv_Rec *) PC;
    (*__gl_dispatch.dispatch.Lightiv)(data->light, data->pname, 
	    (const GLint *) (PC + sizeof(struct __gllc_Lightiv_Rec)));
    arraySize = __GL64PAD(__glLightiv_size(data->pname) * 4);
    size = (GLuint)sizeof(struct __gllc_Lightiv_Rec) + arraySize;
    return PC + size;
}

const GLubyte *__glle_LightModelfv(const GLubyte *PC)
{
    GLuint size;
    GLuint arraySize;
    const struct __gllc_LightModelfv_Rec *data;

    data = (const struct __gllc_LightModelfv_Rec *) PC;
    (*__gl_dispatch.dispatch.LightModelfv)(data->pname, 
	    (const GLfloat *) (PC + sizeof(struct __gllc_LightModelfv_Rec)));
    arraySize = __GL64PAD(__glLightModelfv_size(data->pname) * 4);
    size = (GLuint)sizeof(struct __gllc_LightModelfv_Rec) + arraySize;
    return PC + size;
}

const GLubyte *__glle_LightModeliv(const GLubyte *PC)
{
    GLuint size;
    GLuint arraySize;
    const struct __gllc_LightModeliv_Rec *data;

    data = (const struct __gllc_LightModeliv_Rec *) PC;
    (*__gl_dispatch.dispatch.LightModeliv)(data->pname, 
	    (const GLint *) (PC + sizeof(struct __gllc_LightModeliv_Rec)));
    arraySize = __GL64PAD(__glLightModeliv_size(data->pname) * 4);
    size = (GLuint)sizeof(struct __gllc_LightModeliv_Rec) + arraySize;
    return PC + size;
}

const GLubyte *__glle_LineStipple(const GLubyte *PC)
{
    const struct __gllc_LineStipple_Rec *data;

    data = (const struct __gllc_LineStipple_Rec *) PC;
    (*__gl_dispatch.dispatch.LineStipple)(data->factor, data->pattern);
    return PC + sizeof(struct __gllc_LineStipple_Rec);
}

const GLubyte *__glle_LineWidth(const GLubyte *PC)
{
    const struct __gllc_LineWidth_Rec *data;

    data = (const struct __gllc_LineWidth_Rec *) PC;
    (*__gl_dispatch.dispatch.LineWidth)(data->width);
    return PC + sizeof(struct __gllc_LineWidth_Rec);
}

const GLubyte *__glle_Materialfv(const GLubyte *PC)
{
    GLuint size;
    GLuint arraySize;
    const struct __gllc_Materialfv_Rec *data;

    data = (const struct __gllc_Materialfv_Rec *) PC;
    (*__gl_dispatch.dispatch.Materialfv)(data->face, data->pname, 
	    (const GLfloat *) (PC + sizeof(struct __gllc_Materialfv_Rec)));
    arraySize = __GL64PAD(__glMaterialfv_size(data->pname) * 4);
    size = (GLuint)sizeof(struct __gllc_Materialfv_Rec) + arraySize;
    return PC + size;
}

const GLubyte *__glle_Materialiv(const GLubyte *PC)
{
    GLuint size;
    GLuint arraySize;
    const struct __gllc_Materialiv_Rec *data;

    data = (const struct __gllc_Materialiv_Rec *) PC;
    (*__gl_dispatch.dispatch.Materialiv)(data->face, data->pname, 
	    (const GLint *) (PC + sizeof(struct __gllc_Materialiv_Rec)));
    arraySize = __GL64PAD(__glMaterialiv_size(data->pname) * 4);
    size = (GLuint)sizeof(struct __gllc_Materialiv_Rec) + arraySize;
    return PC + size;
}

const GLubyte *__glle_PointSize(const GLubyte *PC)
{
    const struct __gllc_PointSize_Rec *data;

    data = (const struct __gllc_PointSize_Rec *) PC;
    (*__gl_dispatch.dispatch.PointSize)(data->size);
    return PC + sizeof(struct __gllc_PointSize_Rec);
}

const GLubyte *__glle_PolygonMode(const GLubyte *PC)
{
    const struct __gllc_PolygonMode_Rec *data;

    data = (const struct __gllc_PolygonMode_Rec *) PC;
    (*__gl_dispatch.dispatch.PolygonMode)(data->face, data->mode);
    return PC + sizeof(struct __gllc_PolygonMode_Rec);
}

const GLubyte *__glle_Scissor(const GLubyte *PC)
{
    const struct __gllc_Scissor_Rec *data;

    data = (const struct __gllc_Scissor_Rec *) PC;
    (*__gl_dispatch.dispatch.Scissor)(data->x, data->y, data->width, data->height);
    return PC + sizeof(struct __gllc_Scissor_Rec);
}

const GLubyte *__glle_ShadeModel(const GLubyte *PC)
{
    const struct __gllc_ShadeModel_Rec *data;

    data = (const struct __gllc_ShadeModel_Rec *) PC;
    (*__gl_dispatch.dispatch.ShadeModel)(data->mode);
    return PC + sizeof(struct __gllc_ShadeModel_Rec);
}

const GLubyte *__glle_TexParameterfv(const GLubyte *PC)
{
    GLuint size;
    GLuint arraySize;
    const struct __gllc_TexParameterfv_Rec *data;

    data = (const struct __gllc_TexParameterfv_Rec *) PC;
    (*__gl_dispatch.dispatch.TexParameterfv)(data->target, data->pname, 
	    (const GLfloat *) (PC + sizeof(struct __gllc_TexParameterfv_Rec)));
    arraySize = __GL64PAD(__glTexParameterfv_size(data->pname) * 4);
    size = (GLuint)sizeof(struct __gllc_TexParameterfv_Rec) + arraySize;
    return PC + size;
}

const GLubyte *__glle_TexParameteriv(const GLubyte *PC)
{
    GLuint size;
    GLuint arraySize;
    const struct __gllc_TexParameteriv_Rec *data;

    data = (const struct __gllc_TexParameteriv_Rec *) PC;
    (*__gl_dispatch.dispatch.TexParameteriv)(data->target, data->pname, 
	    (const GLint *) (PC + sizeof(struct __gllc_TexParameteriv_Rec)));
    arraySize = __GL64PAD(__glTexParameteriv_size(data->pname) * 4);
    size = (GLuint)sizeof(struct __gllc_TexParameteriv_Rec) + arraySize;
    return PC + size;
}

const GLubyte *__glle_TexEnvfv(const GLubyte *PC)
{
    GLuint size;
    GLuint arraySize;
    const struct __gllc_TexEnvfv_Rec *data;

    data = (const struct __gllc_TexEnvfv_Rec *) PC;
    (*__gl_dispatch.dispatch.TexEnvfv)(data->target, data->pname, 
	    (const GLfloat *) (PC + sizeof(struct __gllc_TexEnvfv_Rec)));
    arraySize = __GL64PAD(__glTexEnvfv_size(data->pname) * 4);
    size = (GLuint)sizeof(struct __gllc_TexEnvfv_Rec) + arraySize;
    return PC + size;
}

const GLubyte *__glle_TexEnviv(const GLubyte *PC)
{
    GLuint size;
    GLuint arraySize;
    const struct __gllc_TexEnviv_Rec *data;

    data = (const struct __gllc_TexEnviv_Rec *) PC;
    (*__gl_dispatch.dispatch.TexEnviv)(data->target, data->pname, 
	    (const GLint *) (PC + sizeof(struct __gllc_TexEnviv_Rec)));
    arraySize = __GL64PAD(__glTexEnviv_size(data->pname) * 4);
    size = (GLuint)sizeof(struct __gllc_TexEnviv_Rec) + arraySize;
    return PC + size;
}

const GLubyte *__glle_TexGendv(const GLubyte *PC)
{
    GLuint size;
    GLuint arraySize;
    const struct __gllc_TexGendv_Rec *data;

    data = (const struct __gllc_TexGendv_Rec *) PC;
    (*__gl_dispatch.dispatch.TexGendv)(data->coord, data->pname, 
	    (const GLdouble *) (PC + sizeof(struct __gllc_TexGendv_Rec)));
    arraySize = __GL64PAD(__glTexGendv_size(data->pname) * 8);
    size = (GLuint)sizeof(struct __gllc_TexGendv_Rec) + arraySize;
    return PC + size;
}

const GLubyte *__glle_TexGenfv(const GLubyte *PC)
{
    GLuint size;
    GLuint arraySize;
    const struct __gllc_TexGenfv_Rec *data;

    data = (const struct __gllc_TexGenfv_Rec *) PC;
    (*__gl_dispatch.dispatch.TexGenfv)(data->coord, data->pname, 
	    (const GLfloat *) (PC + sizeof(struct __gllc_TexGenfv_Rec)));
    arraySize = __GL64PAD(__glTexGenfv_size(data->pname) * 4);
    size = (GLuint)sizeof(struct __gllc_TexGenfv_Rec) + arraySize;
    return PC + size;
}

const GLubyte *__glle_TexGeniv(const GLubyte *PC)
{
    GLuint size;
    GLuint arraySize;
    const struct __gllc_TexGeniv_Rec *data;

    data = (const struct __gllc_TexGeniv_Rec *) PC;
    (*__gl_dispatch.dispatch.TexGeniv)(data->coord, data->pname, 
	    (const GLint *) (PC + sizeof(struct __gllc_TexGeniv_Rec)));
    arraySize = __GL64PAD(__glTexGeniv_size(data->pname) * 4);
    size = (GLuint)sizeof(struct __gllc_TexGeniv_Rec) + arraySize;
    return PC + size;
}

const GLubyte *__glle_InitNames(const GLubyte *PC)
{

    (*__gl_dispatch.dispatch.InitNames)();
    return PC;
}

const GLubyte *__glle_LoadName(const GLubyte *PC)
{
    const struct __gllc_LoadName_Rec *data;

    data = (const struct __gllc_LoadName_Rec *) PC;
    (*__gl_dispatch.dispatch.LoadName)(data->name);
    return PC + sizeof(struct __gllc_LoadName_Rec);
}

const GLubyte *__glle_PassThrough(const GLubyte *PC)
{
    const struct __gllc_PassThrough_Rec *data;

    data = (const struct __gllc_PassThrough_Rec *) PC;
    (*__gl_dispatch.dispatch.PassThrough)(data->token);
    return PC + sizeof(struct __gllc_PassThrough_Rec);
}

const GLubyte *__glle_PopName(const GLubyte *PC)
{

    (*__gl_dispatch.dispatch.PopName)();
    return PC;
}

const GLubyte *__glle_PushName(const GLubyte *PC)
{
    const struct __gllc_PushName_Rec *data;

    data = (const struct __gllc_PushName_Rec *) PC;
    (*__gl_dispatch.dispatch.PushName)(data->name);
    return PC + sizeof(struct __gllc_PushName_Rec);
}

const GLubyte *__glle_DrawBuffer(const GLubyte *PC)
{
    const struct __gllc_DrawBuffer_Rec *data;

    data = (const struct __gllc_DrawBuffer_Rec *) PC;
    (*__gl_dispatch.dispatch.DrawBuffer)(data->mode);
    return PC + sizeof(struct __gllc_DrawBuffer_Rec);
}

const GLubyte *__glle_Clear(const GLubyte *PC)
{
    const struct __gllc_Clear_Rec *data;

    data = (const struct __gllc_Clear_Rec *) PC;
    (*__gl_dispatch.dispatch.Clear)(data->mask);
    return PC + sizeof(struct __gllc_Clear_Rec);
}

const GLubyte *__glle_ClearAccum(const GLubyte *PC)
{
    const struct __gllc_ClearAccum_Rec *data;

    data = (const struct __gllc_ClearAccum_Rec *) PC;
    (*__gl_dispatch.dispatch.ClearAccum)(data->red, data->green, data->blue, data->alpha);
    return PC + sizeof(struct __gllc_ClearAccum_Rec);
}

const GLubyte *__glle_ClearIndex(const GLubyte *PC)
{
    const struct __gllc_ClearIndex_Rec *data;

    data = (const struct __gllc_ClearIndex_Rec *) PC;
    (*__gl_dispatch.dispatch.ClearIndex)(data->c);
    return PC + sizeof(struct __gllc_ClearIndex_Rec);
}

const GLubyte *__glle_ClearColor(const GLubyte *PC)
{
    const struct __gllc_ClearColor_Rec *data;

    data = (const struct __gllc_ClearColor_Rec *) PC;
    (*__gl_dispatch.dispatch.ClearColor)(data->red, data->green, data->blue, data->alpha);
    return PC + sizeof(struct __gllc_ClearColor_Rec);
}

const GLubyte *__glle_ClearStencil(const GLubyte *PC)
{
    const struct __gllc_ClearStencil_Rec *data;

    data = (const struct __gllc_ClearStencil_Rec *) PC;
    (*__gl_dispatch.dispatch.ClearStencil)(data->s);
    return PC + sizeof(struct __gllc_ClearStencil_Rec);
}

const GLubyte *__glle_ClearDepth(const GLubyte *PC)
{
    const struct __gllc_ClearDepth_Rec *data;

    data = (const struct __gllc_ClearDepth_Rec *) PC;
    (*__gl_dispatch.dispatch.ClearDepth)(data->depth);
    return PC + sizeof(struct __gllc_ClearDepth_Rec);
}

const GLubyte *__glle_StencilMask(const GLubyte *PC)
{
    const struct __gllc_StencilMask_Rec *data;

    data = (const struct __gllc_StencilMask_Rec *) PC;
    (*__gl_dispatch.dispatch.StencilMask)(data->mask);
    return PC + sizeof(struct __gllc_StencilMask_Rec);
}

const GLubyte *__glle_ColorMask(const GLubyte *PC)
{
    const struct __gllc_ColorMask_Rec *data;

    data = (const struct __gllc_ColorMask_Rec *) PC;
    (*__gl_dispatch.dispatch.ColorMask)(data->red, data->green, data->blue, data->alpha);
    return PC + sizeof(struct __gllc_ColorMask_Rec);
}

const GLubyte *__glle_DepthMask(const GLubyte *PC)
{
    const struct __gllc_DepthMask_Rec *data;

    data = (const struct __gllc_DepthMask_Rec *) PC;
    (*__gl_dispatch.dispatch.DepthMask)(data->flag);
    return PC + sizeof(struct __gllc_DepthMask_Rec);
}

const GLubyte *__glle_IndexMask(const GLubyte *PC)
{
    const struct __gllc_IndexMask_Rec *data;

    data = (const struct __gllc_IndexMask_Rec *) PC;
    (*__gl_dispatch.dispatch.IndexMask)(data->mask);
    return PC + sizeof(struct __gllc_IndexMask_Rec);
}

const GLubyte *__glle_Accum(const GLubyte *PC)
{
    const struct __gllc_Accum_Rec *data;

    data = (const struct __gllc_Accum_Rec *) PC;
    (*__gl_dispatch.dispatch.Accum)(data->op, data->value);
    return PC + sizeof(struct __gllc_Accum_Rec);
}

const GLubyte *__glle_PopAttrib(const GLubyte *PC)
{

    (*__gl_dispatch.dispatch.PopAttrib)();
    return PC;
}

const GLubyte *__glle_PushAttrib(const GLubyte *PC)
{
    const struct __gllc_PushAttrib_Rec *data;

    data = (const struct __gllc_PushAttrib_Rec *) PC;
    (*__gl_dispatch.dispatch.PushAttrib)(data->mask);
    return PC + sizeof(struct __gllc_PushAttrib_Rec);
}

const GLubyte *__glle_MapGrid1d(const GLubyte *PC)
{
    const struct __gllc_MapGrid1d_Rec *data;

    data = (const struct __gllc_MapGrid1d_Rec *) PC;
    (*__gl_dispatch.dispatch.MapGrid1d)(data->un, data->u1, data->u2);
    return PC + sizeof(struct __gllc_MapGrid1d_Rec);
}

const GLubyte *__glle_MapGrid1f(const GLubyte *PC)
{
    const struct __gllc_MapGrid1f_Rec *data;

    data = (const struct __gllc_MapGrid1f_Rec *) PC;
    (*__gl_dispatch.dispatch.MapGrid1f)(data->un, data->u1, data->u2);
    return PC + sizeof(struct __gllc_MapGrid1f_Rec);
}

const GLubyte *__glle_MapGrid2d(const GLubyte *PC)
{
    const struct __gllc_MapGrid2d_Rec *data;

    data = (const struct __gllc_MapGrid2d_Rec *) PC;
    (*__gl_dispatch.dispatch.MapGrid2d)(data->un, data->u1, data->u2, data->vn, 
	    data->v1, data->v2);
    return PC + sizeof(struct __gllc_MapGrid2d_Rec);
}

const GLubyte *__glle_MapGrid2f(const GLubyte *PC)
{
    const struct __gllc_MapGrid2f_Rec *data;

    data = (const struct __gllc_MapGrid2f_Rec *) PC;
    (*__gl_dispatch.dispatch.MapGrid2f)(data->un, data->u1, data->u2, data->vn, 
	    data->v1, data->v2);
    return PC + sizeof(struct __gllc_MapGrid2f_Rec);
}

const GLubyte *__glle_EvalCoord1dv(const GLubyte *PC)
{
    const struct __gllc_EvalCoord1dv_Rec *data;

    data = (const struct __gllc_EvalCoord1dv_Rec *) PC;
    (*__gl_dispatch.dispatch.EvalCoord1dv)(data->u);
    return PC + sizeof(struct __gllc_EvalCoord1dv_Rec);
}

const GLubyte *__glle_EvalCoord1fv(const GLubyte *PC)
{
    const struct __gllc_EvalCoord1fv_Rec *data;

    data = (const struct __gllc_EvalCoord1fv_Rec *) PC;
    (*__gl_dispatch.dispatch.EvalCoord1fv)(data->u);
    return PC + sizeof(struct __gllc_EvalCoord1fv_Rec);
}

const GLubyte *__glle_EvalCoord2dv(const GLubyte *PC)
{
    const struct __gllc_EvalCoord2dv_Rec *data;

    data = (const struct __gllc_EvalCoord2dv_Rec *) PC;
    (*__gl_dispatch.dispatch.EvalCoord2dv)(data->u);
    return PC + sizeof(struct __gllc_EvalCoord2dv_Rec);
}

const GLubyte *__glle_EvalCoord2fv(const GLubyte *PC)
{
    const struct __gllc_EvalCoord2fv_Rec *data;

    data = (const struct __gllc_EvalCoord2fv_Rec *) PC;
    (*__gl_dispatch.dispatch.EvalCoord2fv)(data->u);
    return PC + sizeof(struct __gllc_EvalCoord2fv_Rec);
}

const GLubyte *__glle_EvalMesh1(const GLubyte *PC)
{
    const struct __gllc_EvalMesh1_Rec *data;

    data = (const struct __gllc_EvalMesh1_Rec *) PC;
    (*__gl_dispatch.dispatch.EvalMesh1)(data->mode, data->i1, data->i2);
    return PC + sizeof(struct __gllc_EvalMesh1_Rec);
}

const GLubyte *__glle_EvalPoint1(const GLubyte *PC)
{
    const struct __gllc_EvalPoint1_Rec *data;

    data = (const struct __gllc_EvalPoint1_Rec *) PC;
    (*__gl_dispatch.dispatch.EvalPoint1)(data->i);
    return PC + sizeof(struct __gllc_EvalPoint1_Rec);
}

const GLubyte *__glle_EvalMesh2(const GLubyte *PC)
{
    const struct __gllc_EvalMesh2_Rec *data;

    data = (const struct __gllc_EvalMesh2_Rec *) PC;
    (*__gl_dispatch.dispatch.EvalMesh2)(data->mode, data->i1, data->i2, data->j1, 
	    data->j2);
    return PC + sizeof(struct __gllc_EvalMesh2_Rec);
}

const GLubyte *__glle_EvalPoint2(const GLubyte *PC)
{
    const struct __gllc_EvalPoint2_Rec *data;

    data = (const struct __gllc_EvalPoint2_Rec *) PC;
    (*__gl_dispatch.dispatch.EvalPoint2)(data->i, data->j);
    return PC + sizeof(struct __gllc_EvalPoint2_Rec);
}

const GLubyte *__glle_AlphaFunc(const GLubyte *PC)
{
    const struct __gllc_AlphaFunc_Rec *data;

    data = (const struct __gllc_AlphaFunc_Rec *) PC;
    (*__gl_dispatch.dispatch.AlphaFunc)(data->func, data->ref);
    return PC + sizeof(struct __gllc_AlphaFunc_Rec);
}

const GLubyte *__glle_BlendFunc(const GLubyte *PC)
{
    const struct __gllc_BlendFunc_Rec *data;

    data = (const struct __gllc_BlendFunc_Rec *) PC;
    (*__gl_dispatch.dispatch.BlendFunc)(data->sfactor, data->dfactor);
    return PC + sizeof(struct __gllc_BlendFunc_Rec);
}

const GLubyte *__glle_LogicOp(const GLubyte *PC)
{
    const struct __gllc_LogicOp_Rec *data;

    data = (const struct __gllc_LogicOp_Rec *) PC;
    (*__gl_dispatch.dispatch.LogicOp)(data->opcode);
    return PC + sizeof(struct __gllc_LogicOp_Rec);
}

const GLubyte *__glle_StencilFunc(const GLubyte *PC)
{
    const struct __gllc_StencilFunc_Rec *data;

    data = (const struct __gllc_StencilFunc_Rec *) PC;
    (*__gl_dispatch.dispatch.StencilFunc)(data->func, data->ref, data->mask);
    return PC + sizeof(struct __gllc_StencilFunc_Rec);
}

const GLubyte *__glle_StencilOp(const GLubyte *PC)
{
    const struct __gllc_StencilOp_Rec *data;

    data = (const struct __gllc_StencilOp_Rec *) PC;
    (*__gl_dispatch.dispatch.StencilOp)(data->fail, data->zfail, data->zpass);
    return PC + sizeof(struct __gllc_StencilOp_Rec);
}

const GLubyte *__glle_DepthFunc(const GLubyte *PC)
{
    const struct __gllc_DepthFunc_Rec *data;

    data = (const struct __gllc_DepthFunc_Rec *) PC;
    (*__gl_dispatch.dispatch.DepthFunc)(data->func);
    return PC + sizeof(struct __gllc_DepthFunc_Rec);
}

const GLubyte *__glle_PixelZoom(const GLubyte *PC)
{
    const struct __gllc_PixelZoom_Rec *data;

    data = (const struct __gllc_PixelZoom_Rec *) PC;
    (*__gl_dispatch.dispatch.PixelZoom)(data->xfactor, data->yfactor);
    return PC + sizeof(struct __gllc_PixelZoom_Rec);
}

const GLubyte *__glle_PixelTransferf(const GLubyte *PC)
{
    const struct __gllc_PixelTransferf_Rec *data;

    data = (const struct __gllc_PixelTransferf_Rec *) PC;
    (*__gl_dispatch.dispatch.PixelTransferf)(data->pname, data->param);
    return PC + sizeof(struct __gllc_PixelTransferf_Rec);
}

const GLubyte *__glle_PixelTransferi(const GLubyte *PC)
{
    const struct __gllc_PixelTransferi_Rec *data;

    data = (const struct __gllc_PixelTransferi_Rec *) PC;
    (*__gl_dispatch.dispatch.PixelTransferi)(data->pname, data->param);
    return PC + sizeof(struct __gllc_PixelTransferi_Rec);
}

const GLubyte *__glle_PixelMapfv(const GLubyte *PC)
{
    GLuint size;
    GLuint arraySize;
    const struct __gllc_PixelMapfv_Rec *data;

    data = (const struct __gllc_PixelMapfv_Rec *) PC;
    (*__gl_dispatch.dispatch.PixelMapfv)(data->map, data->mapsize, 
	    (const GLfloat *) (PC + sizeof(struct __gllc_PixelMapfv_Rec)));
    arraySize = __GL64PAD(data->mapsize * 4);
    size = (GLuint)sizeof(struct __gllc_PixelMapfv_Rec) + arraySize;
    return PC + size;
}

const GLubyte *__glle_PixelMapuiv(const GLubyte *PC)
{
    GLuint size;
    GLuint arraySize;
    const struct __gllc_PixelMapuiv_Rec *data;

    data = (const struct __gllc_PixelMapuiv_Rec *) PC;
    (*__gl_dispatch.dispatch.PixelMapuiv)(data->map, data->mapsize, 
	    (const GLuint *) (PC + sizeof(struct __gllc_PixelMapuiv_Rec)));
    arraySize = __GL64PAD(data->mapsize * 4);
    size = (GLuint)sizeof(struct __gllc_PixelMapuiv_Rec) + arraySize;
    return PC + size;
}

const GLubyte *__glle_PixelMapusv(const GLubyte *PC)
{
    GLuint size;
    GLuint arraySize;
    const struct __gllc_PixelMapusv_Rec *data;

    data = (const struct __gllc_PixelMapusv_Rec *) PC;
    (*__gl_dispatch.dispatch.PixelMapusv)(data->map, data->mapsize, 
	    (const GLushort *) (PC + sizeof(struct __gllc_PixelMapusv_Rec)));
    arraySize = __GL_PAD(data->mapsize * 2);
    size = (GLuint)sizeof(struct __gllc_PixelMapusv_Rec) + arraySize;
    return PC + size;
}

const GLubyte *__glle_ReadBuffer(const GLubyte *PC)
{
    const struct __gllc_ReadBuffer_Rec *data;

    data = (const struct __gllc_ReadBuffer_Rec *) PC;
    (*__gl_dispatch.dispatch.ReadBuffer)(data->mode);
    return PC + sizeof(struct __gllc_ReadBuffer_Rec);
}

const GLubyte *__glle_CopyPixels(const GLubyte *PC)
{
    const struct __gllc_CopyPixels_Rec *data;

    data = (const struct __gllc_CopyPixels_Rec *) PC;
    (*__gl_dispatch.dispatch.CopyPixels)(data->x, data->y, data->width, data->height, 
	    data->type);
    return PC + sizeof(struct __gllc_CopyPixels_Rec);
}

const GLubyte *__glle_DepthRange(const GLubyte *PC)
{
    const struct __gllc_DepthRange_Rec *data;

    data = (const struct __gllc_DepthRange_Rec *) PC;
    (*__gl_dispatch.dispatch.DepthRange)(data->zNear, data->zFar);
    return PC + sizeof(struct __gllc_DepthRange_Rec);
}

const GLubyte *__glle_Frustum(const GLubyte *PC)
{
    const struct __gllc_Frustum_Rec *data;

    data = (const struct __gllc_Frustum_Rec *) PC;
    (*__gl_dispatch.dispatch.Frustum)(data->left, data->right, data->bottom, data->top, 
	    data->zNear, data->zFar);
    return PC + sizeof(struct __gllc_Frustum_Rec);
}

const GLubyte *__glle_LoadIdentity(const GLubyte *PC)
{

    (*__gl_dispatch.dispatch.LoadIdentity)();
    return PC;
}

const GLubyte *__glle_LoadMatrixf(const GLubyte *PC)
{
    const struct __gllc_LoadMatrixf_Rec *data;

    data = (const struct __gllc_LoadMatrixf_Rec *) PC;
    (*__gl_dispatch.dispatch.LoadMatrixf)(data->m);
    return PC + sizeof(struct __gllc_LoadMatrixf_Rec);
}

const GLubyte *__glle_LoadMatrixd(const GLubyte *PC)
{
    const struct __gllc_LoadMatrixd_Rec *data;

    data = (const struct __gllc_LoadMatrixd_Rec *) PC;
    (*__gl_dispatch.dispatch.LoadMatrixd)(data->m);
    return PC + sizeof(struct __gllc_LoadMatrixd_Rec);
}

const GLubyte *__glle_MatrixMode(const GLubyte *PC)
{
    const struct __gllc_MatrixMode_Rec *data;

    data = (const struct __gllc_MatrixMode_Rec *) PC;
    (*__gl_dispatch.dispatch.MatrixMode)(data->mode);
    return PC + sizeof(struct __gllc_MatrixMode_Rec);
}

const GLubyte *__glle_MultMatrixf(const GLubyte *PC)
{
    const struct __gllc_MultMatrixf_Rec *data;

    data = (const struct __gllc_MultMatrixf_Rec *) PC;
    (*__gl_dispatch.dispatch.MultMatrixf)(data->m);
    return PC + sizeof(struct __gllc_MultMatrixf_Rec);
}

const GLubyte *__glle_MultMatrixd(const GLubyte *PC)
{
    const struct __gllc_MultMatrixd_Rec *data;

    data = (const struct __gllc_MultMatrixd_Rec *) PC;
    (*__gl_dispatch.dispatch.MultMatrixd)(data->m);
    return PC + sizeof(struct __gllc_MultMatrixd_Rec);
}

const GLubyte *__glle_Ortho(const GLubyte *PC)
{
    const struct __gllc_Ortho_Rec *data;

    data = (const struct __gllc_Ortho_Rec *) PC;
    (*__gl_dispatch.dispatch.Ortho)(data->left, data->right, data->bottom, data->top, 
	    data->zNear, data->zFar);
    return PC + sizeof(struct __gllc_Ortho_Rec);
}

const GLubyte *__glle_PopMatrix(const GLubyte *PC)
{

    (*__gl_dispatch.dispatch.PopMatrix)();
    return PC;
}

const GLubyte *__glle_PushMatrix(const GLubyte *PC)
{

    (*__gl_dispatch.dispatch.PushMatrix)();
    return PC;
}

const GLubyte *__glle_Rotated(const GLubyte *PC)
{
    const struct __gllc_Rotated_Rec *data;

    data = (const struct __gllc_Rotated_Rec *) PC;
    (*__gl_dispatch.dispatch.Rotated)(data->angle, data->x, data->y, data->z);
    return PC + sizeof(struct __gllc_Rotated_Rec);
}

const GLubyte *__glle_Rotatef(const GLubyte *PC)
{
    const struct __gllc_Rotatef_Rec *data;

    data = (const struct __gllc_Rotatef_Rec *) PC;
    (*__gl_dispatch.dispatch.Rotatef)(data->angle, data->x, data->y, data->z);
    return PC + sizeof(struct __gllc_Rotatef_Rec);
}

const GLubyte *__glle_Scaled(const GLubyte *PC)
{
    const struct __gllc_Scaled_Rec *data;

    data = (const struct __gllc_Scaled_Rec *) PC;
    (*__gl_dispatch.dispatch.Scaled)(data->x, data->y, data->z);
    return PC + sizeof(struct __gllc_Scaled_Rec);
}

const GLubyte *__glle_Scalef(const GLubyte *PC)
{
    const struct __gllc_Scalef_Rec *data;

    data = (const struct __gllc_Scalef_Rec *) PC;
    (*__gl_dispatch.dispatch.Scalef)(data->x, data->y, data->z);
    return PC + sizeof(struct __gllc_Scalef_Rec);
}

const GLubyte *__glle_Translated(const GLubyte *PC)
{
    const struct __gllc_Translated_Rec *data;

    data = (const struct __gllc_Translated_Rec *) PC;
    (*__gl_dispatch.dispatch.Translated)(data->x, data->y, data->z);
    return PC + sizeof(struct __gllc_Translated_Rec);
}

const GLubyte *__glle_Translatef(const GLubyte *PC)
{
    const struct __gllc_Translatef_Rec *data;

    data = (const struct __gllc_Translatef_Rec *) PC;
    (*__gl_dispatch.dispatch.Translatef)(data->x, data->y, data->z);
    return PC + sizeof(struct __gllc_Translatef_Rec);
}

const GLubyte *__glle_Viewport(const GLubyte *PC)
{
    const struct __gllc_Viewport_Rec *data;

    data = (const struct __gllc_Viewport_Rec *) PC;
    (*__gl_dispatch.dispatch.Viewport)(data->x, data->y, data->width, data->height);
    return PC + sizeof(struct __gllc_Viewport_Rec);
}

const GLubyte *__glle_PolygonOffset(const GLubyte *PC)
{
    const struct __gllc_PolygonOffset_Rec *data;

    data = (const struct __gllc_PolygonOffset_Rec *) PC;
    (*__gl_dispatch.dispatch.PolygonOffset)(data->factor, data->units);
    return PC + sizeof(struct __gllc_PolygonOffset_Rec);
}

const GLubyte *__glle_CopyTexImage1D(const GLubyte *PC)
{
    const struct __gllc_CopyTexImage1D_Rec *data;

    data = (const struct __gllc_CopyTexImage1D_Rec *) PC;
    (*__gl_dispatch.dispatch.CopyTexImage1D)(data->target, data->level, data->internalformat, data->x, 
	    data->y, data->width, data->border);
    return PC + sizeof(struct __gllc_CopyTexImage1D_Rec);
}

const GLubyte *__glle_CopyTexImage2D(const GLubyte *PC)
{
    const struct __gllc_CopyTexImage2D_Rec *data;

    data = (const struct __gllc_CopyTexImage2D_Rec *) PC;
    (*__gl_dispatch.dispatch.CopyTexImage2D)(data->target, data->level, data->internalformat, data->x, 
	    data->y, data->width, data->height, data->border);
    return PC + sizeof(struct __gllc_CopyTexImage2D_Rec);
}

const GLubyte *__glle_CopyTexSubImage1D(const GLubyte *PC)
{
    const struct __gllc_CopyTexSubImage1D_Rec *data;

    data = (const struct __gllc_CopyTexSubImage1D_Rec *) PC;
    (*__gl_dispatch.dispatch.CopyTexSubImage1D)(data->target, data->level, data->xoffset, data->x, 
	    data->y, data->width);
    return PC + sizeof(struct __gllc_CopyTexSubImage1D_Rec);
}

const GLubyte *__glle_CopyTexSubImage2D(const GLubyte *PC)
{
    const struct __gllc_CopyTexSubImage2D_Rec *data;

    data = (const struct __gllc_CopyTexSubImage2D_Rec *) PC;
    (*__gl_dispatch.dispatch.CopyTexSubImage2D)(data->target, data->level, data->xoffset, data->yoffset, 
	    data->x, data->y, data->width, data->height);
    return PC + sizeof(struct __gllc_CopyTexSubImage2D_Rec);
}

const GLubyte *__glle_BindTexture(const GLubyte *PC)
{
    const struct __gllc_BindTexture_Rec *data;

    data = (const struct __gllc_BindTexture_Rec *) PC;
    (*__gl_dispatch.dispatch.BindTexture)(data->target, data->texture);
    return PC + sizeof(struct __gllc_BindTexture_Rec);
}

const GLubyte *__glle_PrioritizeTextures(const GLubyte *PC)
{
    GLuint size;
    GLuint arraySize0;
    GLuint arraySize1;
    const struct __gllc_PrioritizeTextures_Rec *data;

    data = (const struct __gllc_PrioritizeTextures_Rec *) PC;
    arraySize0 = __GL64PAD(data->n * 4);
    arraySize1 = __GL64PAD(data->n * 4);
    size = (GLuint)sizeof(struct __gllc_PrioritizeTextures_Rec) + arraySize0 + arraySize1;
    (*__gl_dispatch.dispatch.PrioritizeTextures)(data->n, 
	    (const GLuint *) (PC + sizeof(struct __gllc_PrioritizeTextures_Rec)), 
	    (const GLclampf *) (PC + sizeof(struct __gllc_PrioritizeTextures_Rec) + arraySize0));
    return PC + size;
}

const GLubyte *__glle_Indexubv(const GLubyte *PC)
{
    const struct __gllc_Indexubv_Rec *data;

    data = (const struct __gllc_Indexubv_Rec *) PC;
    (*__gl_dispatch.dispatch.Indexubv)(data->c);
    return PC + sizeof(struct __gllc_Indexubv_Rec);
}

const GLubyte *__glle_BlendColor(const GLubyte *PC)
{
    const struct __gllc_BlendColor_Rec *data;

    data = (const struct __gllc_BlendColor_Rec *) PC;
    (*__gl_dispatch.dispatch.BlendColor)(data->red, data->green, data->blue, data->alpha);
    return PC + sizeof(struct __gllc_BlendColor_Rec);
}

const GLubyte *__glle_BlendEquation(const GLubyte *PC)
{
    const struct __gllc_BlendEquation_Rec *data;

    data = (const struct __gllc_BlendEquation_Rec *) PC;
    (*__gl_dispatch.dispatch.BlendEquation)(data->mode);
    return PC + sizeof(struct __gllc_BlendEquation_Rec);
}

const GLubyte *__glle_ColorTableParameterfv(const GLubyte *PC)
{
    GLuint size;
    GLuint arraySize;
    const struct __gllc_ColorTableParameterfv_Rec *data;

    data = (const struct __gllc_ColorTableParameterfv_Rec *) PC;
    (*__gl_dispatch.dispatch.ColorTableParameterfv)(data->target, data->pname, 
	    (const GLfloat *) (PC + sizeof(struct __gllc_ColorTableParameterfv_Rec)));
    arraySize = __GL64PAD(__glColorTableParameterfv_size(data->pname) * 4);
    size = (GLuint)sizeof(struct __gllc_ColorTableParameterfv_Rec) + arraySize;
    return PC + size;
}

const GLubyte *__glle_ColorTableParameteriv(const GLubyte *PC)
{
    GLuint size;
    GLuint arraySize;
    const struct __gllc_ColorTableParameteriv_Rec *data;

    data = (const struct __gllc_ColorTableParameteriv_Rec *) PC;
    (*__gl_dispatch.dispatch.ColorTableParameteriv)(data->target, data->pname, 
	    (const GLint *) (PC + sizeof(struct __gllc_ColorTableParameteriv_Rec)));
    arraySize = __GL64PAD(__glColorTableParameteriv_size(data->pname) * 4);
    size = (GLuint)sizeof(struct __gllc_ColorTableParameteriv_Rec) + arraySize;
    return PC + size;
}

const GLubyte *__glle_CopyColorTable(const GLubyte *PC)
{
    const struct __gllc_CopyColorTable_Rec *data;

    data = (const struct __gllc_CopyColorTable_Rec *) PC;
    (*__gl_dispatch.dispatch.CopyColorTable)(data->target, data->internalformat, data->x, data->y, 
	    data->width);
    return PC + sizeof(struct __gllc_CopyColorTable_Rec);
}

const GLubyte *__glle_CopyColorSubTable(const GLubyte *PC)
{
    const struct __gllc_CopyColorSubTable_Rec *data;

    data = (const struct __gllc_CopyColorSubTable_Rec *) PC;
    (*__gl_dispatch.dispatch.CopyColorSubTable)(data->target, data->start, data->x, data->y, 
	    data->width);
    return PC + sizeof(struct __gllc_CopyColorSubTable_Rec);
}

const GLubyte *__glle_ConvolutionParameterf(const GLubyte *PC)
{
    const struct __gllc_ConvolutionParameterf_Rec *data;

    data = (const struct __gllc_ConvolutionParameterf_Rec *) PC;
    (*__gl_dispatch.dispatch.ConvolutionParameterf)(data->target, data->pname, data->params);
    return PC + sizeof(struct __gllc_ConvolutionParameterf_Rec);
}

const GLubyte *__glle_ConvolutionParameterfv(const GLubyte *PC)
{
    GLuint size;
    GLuint arraySize;
    const struct __gllc_ConvolutionParameterfv_Rec *data;

    data = (const struct __gllc_ConvolutionParameterfv_Rec *) PC;
    (*__gl_dispatch.dispatch.ConvolutionParameterfv)(data->target, data->pname, 
	    (const GLfloat *) (PC + sizeof(struct __gllc_ConvolutionParameterfv_Rec)));
    arraySize = __GL64PAD(__glConvolutionParameterfv_size(data->pname) * 4);
    size = (GLuint)sizeof(struct __gllc_ConvolutionParameterfv_Rec) + arraySize;
    return PC + size;
}

const GLubyte *__glle_ConvolutionParameteri(const GLubyte *PC)
{
    const struct __gllc_ConvolutionParameteri_Rec *data;

    data = (const struct __gllc_ConvolutionParameteri_Rec *) PC;
    (*__gl_dispatch.dispatch.ConvolutionParameteri)(data->target, data->pname, data->params);
    return PC + sizeof(struct __gllc_ConvolutionParameteri_Rec);
}

const GLubyte *__glle_ConvolutionParameteriv(const GLubyte *PC)
{
    GLuint size;
    GLuint arraySize;
    const struct __gllc_ConvolutionParameteriv_Rec *data;

    data = (const struct __gllc_ConvolutionParameteriv_Rec *) PC;
    (*__gl_dispatch.dispatch.ConvolutionParameteriv)(data->target, data->pname, 
	    (const GLint *) (PC + sizeof(struct __gllc_ConvolutionParameteriv_Rec)));
    arraySize = __GL64PAD(__glConvolutionParameteriv_size(data->pname) * 4);
    size = (GLuint)sizeof(struct __gllc_ConvolutionParameteriv_Rec) + arraySize;
    return PC + size;
}

const GLubyte *__glle_CopyConvolutionFilter1D(const GLubyte *PC)
{
    const struct __gllc_CopyConvolutionFilter1D_Rec *data;

    data = (const struct __gllc_CopyConvolutionFilter1D_Rec *) PC;
    (*__gl_dispatch.dispatch.CopyConvolutionFilter1D)(data->target, data->internalformat, data->x, data->y, 
	    data->width);
    return PC + sizeof(struct __gllc_CopyConvolutionFilter1D_Rec);
}

const GLubyte *__glle_CopyConvolutionFilter2D(const GLubyte *PC)
{
    const struct __gllc_CopyConvolutionFilter2D_Rec *data;

    data = (const struct __gllc_CopyConvolutionFilter2D_Rec *) PC;
    (*__gl_dispatch.dispatch.CopyConvolutionFilter2D)(data->target, data->internalformat, data->x, data->y, 
	    data->width, data->height);
    return PC + sizeof(struct __gllc_CopyConvolutionFilter2D_Rec);
}

const GLubyte *__glle_Minmax(const GLubyte *PC)
{
    const struct __gllc_Minmax_Rec *data;

    data = (const struct __gllc_Minmax_Rec *) PC;
    (*__gl_dispatch.dispatch.Minmax)(data->target, data->internalformat, data->sink);
    return PC + sizeof(struct __gllc_Minmax_Rec);
}

const GLubyte *__glle_ResetHistogram(const GLubyte *PC)
{
    const struct __gllc_ResetHistogram_Rec *data;

    data = (const struct __gllc_ResetHistogram_Rec *) PC;
    (*__gl_dispatch.dispatch.ResetHistogram)(data->target);
    return PC + sizeof(struct __gllc_ResetHistogram_Rec);
}

const GLubyte *__glle_ResetMinmax(const GLubyte *PC)
{
    const struct __gllc_ResetMinmax_Rec *data;

    data = (const struct __gllc_ResetMinmax_Rec *) PC;
    (*__gl_dispatch.dispatch.ResetMinmax)(data->target);
    return PC + sizeof(struct __gllc_ResetMinmax_Rec);
}

const GLubyte *__glle_CopyTexSubImage3D(const GLubyte *PC)
{
    const struct __gllc_CopyTexSubImage3D_Rec *data;

    data = (const struct __gllc_CopyTexSubImage3D_Rec *) PC;
    (*__gl_dispatch.dispatch.CopyTexSubImage3D)(data->target, data->level, data->xoffset, data->yoffset, 
	    data->zoffset, data->x, data->y, data->width, data->height);
    return PC + sizeof(struct __gllc_CopyTexSubImage3D_Rec);
}

const GLubyte *__glle_ActiveTextureARB(const GLubyte *PC)
{
    const struct __gllc_ActiveTextureARB_Rec *data;

    data = (const struct __gllc_ActiveTextureARB_Rec *) PC;
    (*__gl_dispatch.dispatch.ActiveTextureARB)(data->texture);
    return PC + sizeof(struct __gllc_ActiveTextureARB_Rec);
}

const GLubyte *__glle_MultiTexCoord1dvARB(const GLubyte *PC)
{
    const struct __gllc_MultiTexCoord1dvARB_Rec *data;

    data = (const struct __gllc_MultiTexCoord1dvARB_Rec *) PC;
    (*__gl_dispatch.dispatch.MultiTexCoord1dvARB)(data->target, data->v);
    return PC + sizeof(struct __gllc_MultiTexCoord1dvARB_Rec);
}

const GLubyte *__glle_MultiTexCoord1fvARB(const GLubyte *PC)
{
    const struct __gllc_MultiTexCoord1fvARB_Rec *data;

    data = (const struct __gllc_MultiTexCoord1fvARB_Rec *) PC;
    (*__gl_dispatch.dispatch.MultiTexCoord1fvARB)(data->target, data->v);
    return PC + sizeof(struct __gllc_MultiTexCoord1fvARB_Rec);
}

const GLubyte *__glle_MultiTexCoord1ivARB(const GLubyte *PC)
{
    const struct __gllc_MultiTexCoord1ivARB_Rec *data;

    data = (const struct __gllc_MultiTexCoord1ivARB_Rec *) PC;
    (*__gl_dispatch.dispatch.MultiTexCoord1ivARB)(data->target, data->v);
    return PC + sizeof(struct __gllc_MultiTexCoord1ivARB_Rec);
}

const GLubyte *__glle_MultiTexCoord1svARB(const GLubyte *PC)
{
    const struct __gllc_MultiTexCoord1svARB_Rec *data;

    data = (const struct __gllc_MultiTexCoord1svARB_Rec *) PC;
    (*__gl_dispatch.dispatch.MultiTexCoord1svARB)(data->target, data->v);
    return PC + sizeof(struct __gllc_MultiTexCoord1svARB_Rec);
}

const GLubyte *__glle_MultiTexCoord2dvARB(const GLubyte *PC)
{
    const struct __gllc_MultiTexCoord2dvARB_Rec *data;

    data = (const struct __gllc_MultiTexCoord2dvARB_Rec *) PC;
    (*__gl_dispatch.dispatch.MultiTexCoord2dvARB)(data->target, data->v);
    return PC + sizeof(struct __gllc_MultiTexCoord2dvARB_Rec);
}

const GLubyte *__glle_MultiTexCoord2fvARB(const GLubyte *PC)
{
    const struct __gllc_MultiTexCoord2fvARB_Rec *data;

    data = (const struct __gllc_MultiTexCoord2fvARB_Rec *) PC;
    (*__gl_dispatch.dispatch.MultiTexCoord2fvARB)(data->target, data->v);
    return PC + sizeof(struct __gllc_MultiTexCoord2fvARB_Rec);
}

const GLubyte *__glle_MultiTexCoord2ivARB(const GLubyte *PC)
{
    const struct __gllc_MultiTexCoord2ivARB_Rec *data;

    data = (const struct __gllc_MultiTexCoord2ivARB_Rec *) PC;
    (*__gl_dispatch.dispatch.MultiTexCoord2ivARB)(data->target, data->v);
    return PC + sizeof(struct __gllc_MultiTexCoord2ivARB_Rec);
}

const GLubyte *__glle_MultiTexCoord2svARB(const GLubyte *PC)
{
    const struct __gllc_MultiTexCoord2svARB_Rec *data;

    data = (const struct __gllc_MultiTexCoord2svARB_Rec *) PC;
    (*__gl_dispatch.dispatch.MultiTexCoord2svARB)(data->target, data->v);
    return PC + sizeof(struct __gllc_MultiTexCoord2svARB_Rec);
}

const GLubyte *__glle_MultiTexCoord3dvARB(const GLubyte *PC)
{
    const struct __gllc_MultiTexCoord3dvARB_Rec *data;

    data = (const struct __gllc_MultiTexCoord3dvARB_Rec *) PC;
    (*__gl_dispatch.dispatch.MultiTexCoord3dvARB)(data->target, data->v);
    return PC + sizeof(struct __gllc_MultiTexCoord3dvARB_Rec);
}

const GLubyte *__glle_MultiTexCoord3fvARB(const GLubyte *PC)
{
    const struct __gllc_MultiTexCoord3fvARB_Rec *data;

    data = (const struct __gllc_MultiTexCoord3fvARB_Rec *) PC;
    (*__gl_dispatch.dispatch.MultiTexCoord3fvARB)(data->target, data->v);
    return PC + sizeof(struct __gllc_MultiTexCoord3fvARB_Rec);
}

const GLubyte *__glle_MultiTexCoord3ivARB(const GLubyte *PC)
{
    const struct __gllc_MultiTexCoord3ivARB_Rec *data;

    data = (const struct __gllc_MultiTexCoord3ivARB_Rec *) PC;
    (*__gl_dispatch.dispatch.MultiTexCoord3ivARB)(data->target, data->v);
    return PC + sizeof(struct __gllc_MultiTexCoord3ivARB_Rec);
}

const GLubyte *__glle_MultiTexCoord3svARB(const GLubyte *PC)
{
    const struct __gllc_MultiTexCoord3svARB_Rec *data;

    data = (const struct __gllc_MultiTexCoord3svARB_Rec *) PC;
    (*__gl_dispatch.dispatch.MultiTexCoord3svARB)(data->target, data->v);
    return PC + sizeof(struct __gllc_MultiTexCoord3svARB_Rec);
}

const GLubyte *__glle_MultiTexCoord4dvARB(const GLubyte *PC)
{
    const struct __gllc_MultiTexCoord4dvARB_Rec *data;

    data = (const struct __gllc_MultiTexCoord4dvARB_Rec *) PC;
    (*__gl_dispatch.dispatch.MultiTexCoord4dvARB)(data->target, data->v);
    return PC + sizeof(struct __gllc_MultiTexCoord4dvARB_Rec);
}

const GLubyte *__glle_MultiTexCoord4fvARB(const GLubyte *PC)
{
    const struct __gllc_MultiTexCoord4fvARB_Rec *data;

    data = (const struct __gllc_MultiTexCoord4fvARB_Rec *) PC;
    (*__gl_dispatch.dispatch.MultiTexCoord4fvARB)(data->target, data->v);
    return PC + sizeof(struct __gllc_MultiTexCoord4fvARB_Rec);
}

const GLubyte *__glle_MultiTexCoord4ivARB(const GLubyte *PC)
{
    const struct __gllc_MultiTexCoord4ivARB_Rec *data;

    data = (const struct __gllc_MultiTexCoord4ivARB_Rec *) PC;
    (*__gl_dispatch.dispatch.MultiTexCoord4ivARB)(data->target, data->v);
    return PC + sizeof(struct __gllc_MultiTexCoord4ivARB_Rec);
}

const GLubyte *__glle_MultiTexCoord4svARB(const GLubyte *PC)
{
    const struct __gllc_MultiTexCoord4svARB_Rec *data;

    data = (const struct __gllc_MultiTexCoord4svARB_Rec *) PC;
    (*__gl_dispatch.dispatch.MultiTexCoord4svARB)(data->target, data->v);
    return PC + sizeof(struct __gllc_MultiTexCoord4svARB_Rec);
}


