/*
** License Applicability. Except to the extent portions of this file are
** made subject to an alternative license as permitted in the SGI Free
** Software License B, Version 1.1 (the "License"), the contents of this
** file are subject only to the provisions of the License. You may not use
** this file except in compliance with the License. You may obtain a copy
** of the License at Silicon Graphics, Inc., attn: Legal Services, 1600
** Amphitheatre Parkway, Mountain View, CA 94043-1351, or at:
**
** http://oss.sgi.com/projects/FreeB
**
** Note that, as provided in the License, the Software is distributed on an
** "AS IS" basis, with ALL EXPRESS AND IMPLIED WARRANTIES AND CONDITIONS
** DISCLAIMED, INCLUDING, WITHOUT LIMITATION, ANY IMPLIED WARRANTIES AND
** CONDITIONS OF MERCHANTABILITY, SATISFACTORY QUALITY, FITNESS FOR A
** PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
**
** Original Code. The Original Code is: OpenGL Sample Implementation,
** Version 1.2.1, released January 26, 2000, developed by Silicon Graphics,
** License Applicability. Except to the extent portions of this file are
** made subject to an alternative license as permitted in the SGI Free
** Software License B, Version 1.1 (the "License"), the contents of this
** file are subject only to the provisions of the License. You may not use
** this file except in compliance with the License. You may obtain a copy
** of the License at Silicon Graphics, Inc., attn: Legal Services, 1600
** Amphitheatre Parkway, Mountain View, CA 94043-1351, or at:
** 
** http://oss.sgi.com/projects/FreeB
** 
** Note that, as provided in the License, the Software is distributed on an
** "AS IS" basis, with ALL EXPRESS AND IMPLIED WARRANTIES AND CONDITIONS
** DISCLAIMED, INCLUDING, WITHOUT LIMITATION, ANY IMPLIED WARRANTIES AND
** CONDITIONS OF MERCHANTABILITY, SATISFACTORY QUALITY, FITNESS FOR A
** PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
** 
** Original Code. The Original Code is: OpenGL Sample Implementation,
** Version 1.2.1, released January 26, 2000, developed by Silicon Graphics,
** Inc. The Original Code is Copyright (c) 1991-2000 Silicon Graphics, Inc.
** Copyright in any portions created by third parties is as indicated
** elsewhere herein. All Rights Reserved.
** 
** Additional Notice Provisions: The application programming interfaces
** established by SGI in conjunction with the Original Code are The
** OpenGL(R) Graphics System: A Specification (Version 1.2.1), released
** April 1, 1999; The OpenGL(R) Graphics System Utility Library (Version
** 1.3), released November 4, 1998; and OpenGL(R) Graphics with the X
** Window System(R) (Version 1.3), released October 19, 1998. This software
** was created using the OpenGL(R) version 1.2.1 Sample Implementation
** published by SGI, but has not been independently verified as being
** compliant with the OpenGL(R) version 1.2.1 Specification.
**
*/
/* DO NOT EDIT - THIS FILE IS AUTOMATICALLY GENERATED */
#ifndef _g_listop_h_
#define _g_listop_h_

#define __glop_CallList                  0
#define __glop_CallLists                 1
#define __glop_ListBase                  2
#define __glop_Begin                     3
#define __glop_Bitmap                    4
#define __glop_Color3bv                  5
#define __glop_Color3dv                  6
#define __glop_Color3fv                  7
#define __glop_Color3iv                  8
#define __glop_Color3sv                  9
#define __glop_Color3ubv                10
#define __glop_Color3uiv                11
#define __glop_Color3usv                12
#define __glop_Color4bv                 13
#define __glop_Color4dv                 14
#define __glop_Color4fv                 15
#define __glop_Color4iv                 16
#define __glop_Color4sv                 17
#define __glop_Color4ubv                18
#define __glop_Color4uiv                19
#define __glop_Color4usv                20
#define __glop_EdgeFlagv                21
#define __glop_End                      22
#define __glop_Indexdv                  23
#define __glop_Indexfv                  24
#define __glop_Indexiv                  25
#define __glop_Indexsv                  26
#define __glop_Normal3bv                27
#define __glop_Normal3dv                28
#define __glop_Normal3fv                29
#define __glop_Normal3iv                30
#define __glop_Normal3sv                31
#define __glop_RasterPos2dv             32
#define __glop_RasterPos2fv             33
#define __glop_RasterPos2iv             34
#define __glop_RasterPos2sv             35
#define __glop_RasterPos3dv             36
#define __glop_RasterPos3fv             37
#define __glop_RasterPos3iv             38
#define __glop_RasterPos3sv             39
#define __glop_RasterPos4dv             40
#define __glop_RasterPos4fv             41
#define __glop_RasterPos4iv             42
#define __glop_RasterPos4sv             43
#define __glop_Rectdv                   44
#define __glop_Rectfv                   45
#define __glop_Rectiv                   46
#define __glop_Rectsv                   47
#define __glop_TexCoord1dv              48
#define __glop_TexCoord1fv              49
#define __glop_TexCoord1iv              50
#define __glop_TexCoord1sv              51
#define __glop_TexCoord2dv              52
#define __glop_TexCoord2fv              53
#define __glop_TexCoord2iv              54
#define __glop_TexCoord2sv              55
#define __glop_TexCoord3dv              56
#define __glop_TexCoord3fv              57
#define __glop_TexCoord3iv              58
#define __glop_TexCoord3sv              59
#define __glop_TexCoord4dv              60
#define __glop_TexCoord4fv              61
#define __glop_TexCoord4iv              62
#define __glop_TexCoord4sv              63
#define __glop_Vertex2dv                64
#define __glop_Vertex2fv                65
#define __glop_Vertex2iv                66
#define __glop_Vertex2sv                67
#define __glop_Vertex3dv                68
#define __glop_Vertex3fv                69
#define __glop_Vertex3iv                70
#define __glop_Vertex3sv                71
#define __glop_Vertex4dv                72
#define __glop_Vertex4fv                73
#define __glop_Vertex4iv                74
#define __glop_Vertex4sv                75
#define __glop_ClipPlane                76
#define __glop_ColorMaterial            77
#define __glop_CullFace                 78
#define __glop_Fogf                     79
#define __glop_Fogfv                    80
#define __glop_Fogi                     81
#define __glop_Fogiv                    82
#define __glop_FrontFace                83
#define __glop_Hint                     84
#define __glop_Lightf                   85
#define __glop_Lightfv                  86
#define __glop_Lighti                   87
#define __glop_Lightiv                  88
#define __glop_LightModelf              89
#define __glop_LightModelfv             90
#define __glop_LightModeli              91
#define __glop_LightModeliv             92
#define __glop_LineStipple              93
#define __glop_LineWidth                94
#define __glop_Materialf                95
#define __glop_Materialfv               96
#define __glop_Materiali                97
#define __glop_Materialiv               98
#define __glop_PointSize                99
#define __glop_PolygonMode             100
#define __glop_PolygonStipple          101
#define __glop_Scissor                 102
#define __glop_ShadeModel              103
#define __glop_TexParameterf           104
#define __glop_TexParameterfv          105
#define __glop_TexParameteri           106
#define __glop_TexParameteriv          107
#define __glop_TexImage1D              108
#define __glop_TexImage2D              109
#define __glop_TexEnvf                 110
#define __glop_TexEnvfv                111
#define __glop_TexEnvi                 112
#define __glop_TexEnviv                113
#define __glop_TexGend                 114
#define __glop_TexGendv                115
#define __glop_TexGenf                 116
#define __glop_TexGenfv                117
#define __glop_TexGeni                 118
#define __glop_TexGeniv                119
#define __glop_InitNames               120
#define __glop_LoadName                121
#define __glop_PassThrough             122
#define __glop_PopName                 123
#define __glop_PushName                124
#define __glop_DrawBuffer              125
#define __glop_Clear                   126
#define __glop_ClearAccum              127
#define __glop_ClearIndex              128
#define __glop_ClearColor              129
#define __glop_ClearStencil            130
#define __glop_ClearDepth              131
#define __glop_StencilMask             132
#define __glop_ColorMask               133
#define __glop_DepthMask               134
#define __glop_IndexMask               135
#define __glop_Accum                   136
#define __glop_Disable                 137
#define __glop_Enable                  138
#define __glop_PopAttrib               139
#define __glop_PushAttrib              140
#define __glop_Map1d                   141
#define __glop_Map1f                   142
#define __glop_Map2d                   143
#define __glop_Map2f                   144
#define __glop_MapGrid1d               145
#define __glop_MapGrid1f               146
#define __glop_MapGrid2d               147
#define __glop_MapGrid2f               148
#define __glop_EvalCoord1dv            149
#define __glop_EvalCoord1fv            150
#define __glop_EvalCoord2dv            151
#define __glop_EvalCoord2fv            152
#define __glop_EvalMesh1               153
#define __glop_EvalPoint1              154
#define __glop_EvalMesh2               155
#define __glop_EvalPoint2              156
#define __glop_AlphaFunc               157
#define __glop_BlendFunc               158
#define __glop_LogicOp                 159
#define __glop_StencilFunc             160
#define __glop_StencilOp               161
#define __glop_DepthFunc               162
#define __glop_PixelZoom               163
#define __glop_PixelTransferf          164
#define __glop_PixelTransferi          165
#define __glop_PixelMapfv              166
#define __glop_PixelMapuiv             167
#define __glop_PixelMapusv             168
#define __glop_ReadBuffer              169
#define __glop_CopyPixels              170
#define __glop_DrawPixels              171
#define __glop_DepthRange              172
#define __glop_Frustum                 173
#define __glop_LoadIdentity            174
#define __glop_LoadMatrixf             175
#define __glop_LoadMatrixd             176
#define __glop_MatrixMode              177
#define __glop_MultMatrixf             178
#define __glop_MultMatrixd             179
#define __glop_Ortho                   180
#define __glop_PopMatrix               181
#define __glop_PushMatrix              182
#define __glop_Rotated                 183
#define __glop_Rotatef                 184
#define __glop_Scaled                  185
#define __glop_Scalef                  186
#define __glop_Translated              187
#define __glop_Translatef              188
#define __glop_Viewport                189
#define __glop_ArrayElement            190
#define __glop_DrawArrays              191
#define __glop_DrawElements            192
#define __glop_PolygonOffset           193
#define __glop_CopyTexImage1D          194
#define __glop_CopyTexImage2D          195
#define __glop_CopyTexSubImage1D       196
#define __glop_CopyTexSubImage2D       197
#define __glop_TexSubImage1D           198
#define __glop_TexSubImage2D           199
#define __glop_BindTexture             200
#define __glop_PrioritizeTextures      201
#define __glop_Indexubv                202
#define __glop_BlendColor              203
#define __glop_BlendEquation           204
#define __glop_DrawRangeElements       205
#define __glop_ColorTable              206
#define __glop_ColorTableParameterfv    207
#define __glop_ColorTableParameteriv    208
#define __glop_CopyColorTable          209
#define __glop_ColorSubTable           210
#define __glop_CopyColorSubTable       211
#define __glop_ConvolutionFilter1D     212
#define __glop_ConvolutionFilter2D     213
#define __glop_ConvolutionParameterf    214
#define __glop_ConvolutionParameterfv    215
#define __glop_ConvolutionParameteri    216
#define __glop_ConvolutionParameteriv    217
#define __glop_CopyConvolutionFilter1D    218
#define __glop_CopyConvolutionFilter2D    219
#define __glop_SeparableFilter2D       220
#define __glop_Histogram               221
#define __glop_Minmax                  222
#define __glop_ResetHistogram          223
#define __glop_ResetMinmax             224
#define __glop_TexImage3D              225
#define __glop_TexSubImage3D           226
#define __glop_CopyTexSubImage3D       227
#define __glop_ActiveTextureARB        228
#define __glop_MultiTexCoord1dvARB     229
#define __glop_MultiTexCoord1fvARB     230
#define __glop_MultiTexCoord1ivARB     231
#define __glop_MultiTexCoord1svARB     232
#define __glop_MultiTexCoord2dvARB     233
#define __glop_MultiTexCoord2fvARB     234
#define __glop_MultiTexCoord2ivARB     235
#define __glop_MultiTexCoord2svARB     236
#define __glop_MultiTexCoord3dvARB     237
#define __glop_MultiTexCoord3fvARB     238
#define __glop_MultiTexCoord3ivARB     239
#define __glop_MultiTexCoord3svARB     240
#define __glop_MultiTexCoord4dvARB     241
#define __glop_MultiTexCoord4fvARB     242
#define __glop_MultiTexCoord4ivARB     243
#define __glop_MultiTexCoord4svARB     244
#define __glop_ArrayElementEXT         245
#define __glop_DrawArraysEXT           246
#define __GL_NUM_LISTABLE_CMDS 247


#endif  /* _g_listop_h_ */
